### ISSUE TITLE
tslib can help dedupe copies of `__extends`

### ISSUE THREAD

**Issue by DanielRosenwasser** [hotwired/stimulus#300]
I noticed two copies of the `__extends` helper in Stimulus' bundle. No biggie, but [using tslib](https://github.com/Microsoft/tslib/) could probably shave off about 300 bytes post minification, and would help avoid duplication of other helpers for TypeScript users using `@stimulus/core`.

**Comment by javan** [comment]
Happy to merge a PR if you feel like taking this on!
