### ISSUE TITLE
Provide callback to detect controller removal (helps with leaks)

### ISSUE THREAD

**Issue by mildred** [hotwired/stimulus#301]
When using Stimulus with Turbolinks, the controllers have the possibility to live a long time as the page is never truly reloaded. in this circumstance, it is important to dispose the controllers properly once they are no longer needed (such as when Turbolinks reloads the page and replaces the element a controller is attached to)

I think Stimulus should add a callback to allow the controller to detect when it is no longer needed and remove references to itself as to avoid keeping the controller referenced and preventing it to be collected by the garbage collector.

This is important in case there are references pointing to the controller or to the DOM nodes that are kept outside the controller object itself. In the meantime, I'm using the [Node.isConnected](https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected) but this might not always work in case a live controller is detached and reattached afterwards

**Comment by javan** [comment]
To clarify, are you suggesting something different from the [`disconnect()` callback](https://stimulusjs.org/reference/lifecycle-callbacks#methods)?

> **[Disconnection](https://stimulusjs.org/reference/lifecycle-callbacks#disconnection)**
> 
> A connected controller will later become _disconnected_ when either of the preceding conditions becomes false, such as under any of the following scenarios:
> 
> * the element is explicitly removed from the document with `Node#removeChild()` or `ChildNode#remove()`
> * one of the element's parent elements is removed from the document
> * one of the element's parent elements has its contents replaced by `Element#innerHTML=`
> * the element's `data-controller` attribute is removed or modified
> * the document installs a new `<body>` element, such as during a Turbolinks page change
> 
> When a controller becomes disconnected, Stimulus calls its `disconnect()` method.

**Comment by marcelolx** [comment]
@mildred As Javan commented above, the `disconnect` callback doesn't already does the job?
