### ISSUE TITLE
Webpacker 5.1 breaks recommended TypeScript controller pattern

### ISSUE THREAD

**Issue by noelrappin** [hotwired/stimulus#303]
See: https://github.com/rails/webpacker/issues/2558 

Webpacker 5.1 changed the loader for TypeScript, which changed code compilation behavior, which breaks class properties.

So the controller declaration:

I have a simple Stimulus controller, defined to start as follows:

```
import { Controller } from "stimulus"

export default class extends Controller {
  static classes = ["hidden"]
  static targets = ["filterInput", "concert"]

  hiddenClass: string
  concertTargets: HTMLElement[]
  filterInputTarget: HTMLInputElement

  // and so on
```

Now breaks with a `TypeError: Cannot set property hiddenClass of #<extended> which has only a getter`.

**Comment by javan** [comment]
Keeping in mind that Stimulus is a just a JavaScript library with no real connection to Webpacker, how can we help?

**Comment by noelrappin** [comment]
Thanks for the response. 

I think a lot of Stimulus users are probably using Webpacker, and I think this is the Stimulus team's guidance on how to use TypeScript with Stimulus controllers, and it no longer works, so wanted to make the Stimulus team aware of that in case there was a different preferred way to use TypeScript.

**Comment by javan** [comment]
Do you have a sense of where the root "problem" lies? Webpacker? TypeScript? Babel-compiled TypeScript? Other?

**Comment by noelrappin** [comment]
In rails/webpacker#2558, the Webpacker team seems to feel it's a discrepancy between the TC39 proposal and TypeScript, and they think the new Babel version is correct (or at least, they think the Babel team thinks so and is unlikely to change the behavior...)

**Comment by javan** [comment]
Seems like a good use case for the [definite assignment assertion](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#definite-assignment-assertions), no?
```ts
export default class extends Controller {
  static classes = ["hidden"]
 
  hiddenClass!: string
 
  // …
}
```

**Comment by markcatley** [comment]
@javan It seems like it would be. Unfortunately, it seems like that feature doesn't change the runtime behaviour and still causes the error mentioned.

It seems to me like declare fields might be the right approach. I.e.
```typescript
export default class extends Controller {
  static classes = ["hidden"]
 
  declare hiddenClass: string
 
  // …
}
```
However, I don't seem to be able to get the allowDeclareFields @babel/preset-typescript option to work. I get the following error in the browser console:
```
certificates_controller.ts:45 Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: ./app/webpack/controllers/eoi_controller.ts: TypeScript 'declare' fields must first be transformed by @babel/plugin-transform-typescript.
If you have already enabled that plugin (or '@babel/preset-typescript'), make sure that it runs before any plugin related to additional class features:
 - @babel/plugin-proposal-class-properties
 - @babel/plugin-proposal-private-methods
 - @babel/plugin-proposal-decorators
  2 | 
  3 | export default class extends Controller {
> 4 |   declare step1Target: Element;
```

**Comment by zombor** [comment]
I found this closed issue which has a solution that compiles and works: https://github.com/stimulusjs/stimulus/issues/221#issuecomment-457275513

Is this the recommended way to resolve this issue?

**Comment by noelrappin** [comment]
I mean, if it works, I guess I'll switch to it, but I'm not looking forward to explaining it in the book.

The Babel team seems unlikely to change this behavior, so unless TypeScript changes for some reason, I think we're stuck with trying to make this work better on the Stimulus side.

**Comment by markcatley** [comment]
@zombor Thanks for the workaround. It works for me but I totally agree with you @noelrappin not the easiest to understand. Also, thanks for the book - I've been reading the drafts.

**Comment by fleck** [comment]
To fix this I removed `      ['@babel/preset-typescript', { 'allExtensions': true, 'isTSX': true }]` from babel.config.js and added 

`["@babel/plugin-transform-typescript", { 'allExtensions': true, 'isTSX': true, 'allowDeclareFields': true }],` to the top of my plugins entry (anywhere above `@babel/plugin-proposal-class-properties` should work).

This will also allow the use of declare `declare containerTarget: HTMLDialogElement;` which will future proof your controllers should TS ever align more closely with the ECMA spec.

**Comment by noelrappin** [comment]
@fleck Somewhat to my surprise, this works for me if I switch to the plugin, but declare it as `["@babel/plugin-transform-typescript", { 'allExtensions': true, 'isTSX': true, 'allowDeclareFields': false }]` -- not sure why, because as far as I can tell, false is the default. Nevertheless, if I do what you have, I get the same answer, and if I do what I have it works. ???

**Comment by fleck** [comment]
@noelrappin that is curious... but there's a ton of complex transformations going on with TS/Babel so doesn't surprise me that there are edge cases like this. Either way, I think this issue can be closed, seems to be an issue with Babel/TS/Webpacker config.

**Comment by szTheory** [comment]
Ran into this issue after upgrading to Stimulus 2.0, running a Rails app with Webpacker 5.2.1. It complains when you use targets in a Stimulus controller built in TypeScript.

In babel.config.js:

```javascript
    plugins: [
      "babel-plugin-macros",
      "@babel/plugin-syntax-dynamic-import",
      isTestEnv && "babel-plugin-dynamic-import-node",
      "@babel/plugin-transform-destructuring",
      // added this
      [
        "@babel/plugin-transform-typescript",
        { allExtensions: true, isTSX: true, allowDeclareFields: true },
      ],
```

In the TypeScript controller:

```typescript
export default class extends Controller {
  static targets = ["addItem", "template"];

  // TypeScript with Stimulus 2.0 must declare properties
  // https://github.com/stimulusjs/stimulus/issues/303#issuecomment-653630360
  declare templateTarget: HTMLElement;
  declare addItemTarget: HTMLElement;
 ```

**Comment by dhh** [comment]
Let's report or fix in the Webpacker repo ✌️

**Comment by leevigraham** [comment]
@noelrappin @fleck 

I think I've nailed down the error you were getting here:

```
SyntaxError: ./app/webpack/controllers/eoi_controller.ts: TypeScript 'declare' fields must first be transformed by @babel/plugin-transform-typescript.
If you have already enabled that plugin (or '@babel/preset-typescript'), make sure that it runs before any plugin related to additional class features:
 - @babel/plugin-proposal-class-properties
 - @babel/plugin-proposal-private-methods
 - @babel/plugin-proposal-decorators
  2 | 
  3 | export default class extends Controller {
> 4 |   declare step1Target: Element;
```

and why the plugin solution works:

```
Somewhat to my surprise, this works for me if I switch to the plugin, but declare it as ["@babel/plugin-transform-typescript", { 'allExtensions': true, 'isTSX': true, 'allowDeclareFields': false }] -- not sure why, because as far as I can tell, false is the default. Nevertheless, if I do what you have, I get the same answer, and if I do what I have it works. ???
```

It's likely webpacker is adding `@babel/plugin-proposal-class-properties` as a plugin. Plugins are run before presets which leads to the error you're seeing.

Switching to the `@babel/plugin-transform-typescript` which is also included in `@babel/preset-typescript` means it is run first, removing the `declare` keyword (and probably stripping the class field) allowing `@babel/plugin-proposal-class-properties` to work correctly.

if webpacker is using `@babel/preset-typescript` then it's likely that `@babel/plugin-transform-typescript` is being called twice which is potentially slowing down the build.

[Babel 7.14 enables class fields & private methods by default in @babel/preset-env](https://blog.saeloun.com/2021/06/24/babel-enables-class-field-and-private-methods.html) so adding the `@babel/plugin-proposal-class-properties` plugin is not required if you're using Babel 7.14 or greater and `@babel/preset-env`
