### ISSUE TITLE
Unable to reference variable in a class method

### ISSUE THREAD

**Issue by christopheragnus** [hotwired/stimulus#310]
Hi, whats the idiomatic way to reference a variable inside a class method?

I can't use `constructor()` method to assign a public variable or else the controller class stops working, and I can't set `panToArea()` inside `initialize()`, because I need it for StimulusJS action. 

See below -  I can call `map` if I set `Map.prototype.map = map`. Is there an alternative using `this` or `call()`?

```
export default class Map extends Controller {
  static targets = ["Box"];

  initialize = async () => {
  
 // some stuff removed

    try {
      let response = await axios.get("..");
    
// some stuff removed

      const map = L.map(mapBox, {
        center: [1.3521, 103.8198],
        zoom: 3,
        minZoom: 2,
        layers: [
          L.tileLayer(hereTileUrl, { maxZoom: 18, minZoom: 1, noWrap: true })
        ]
      });

      Map.prototype.map = map;

// etc, etc.

    } 

  };

  panToArea = event => {
    this.map.panTo([50, 30]);
  };
}

```

**Comment by dancallaghan** [comment]
@christopheragnus just use `this`

```javascript
this.map = map;
```

Seems you’re initialising the map asynchronously it might be worth checking the map is set in the `panTo` function
