### ISSUE TITLE
The target is not the same as the actually DOM object

### ISSUE THREAD

**Issue by namiwang** [hotwired/stimulus#312]
I'm a little confused about whether this is an issue with stimulus or another component, please bear with me :)

# repro

```
<div data-controller="note">
  <input type="hidden" name="note_content" id="note_content">
  <trix-editor data-target="note.editor" data-action="trix-change->note#update">
…
```

```
export default class extends Controller {
  static targets = ['editor']

  update() {
    this.editorTarget.editor // <- undefined
    document.query('trix-editor').editor // <- a trix editor
  }
…
```

The actual dom object has an `editor` property which is added by trix I believe, and the target assigned by stimulus lacks that.

Not sure if this is expected.

**Comment by BuddyLReno** [comment]
Have you tried to replicate this in something like codepen?

**Comment by BuddyLReno** [comment]
Also, since it looks like trix just sets itself up from what I gather on the documentation, maybe try making sure that the trix script is included before the scripts that create and load your controller?

**Comment by namiwang** [comment]
That's a fare point, will try to reproduce to confirm.

**Comment by marcoroth** [comment]
Hey @namiwang

I'm not sure if something changed in the meantime, but it appears to be working as expected. 

I setup a Glitch Remix and used your code:
https://glitch.com/edit/#!/stimulus-issue-312

Maybe it got fixed unwillingly or something else is going on in your DOM. If you are able to reproduce it somehow I'd be happy to have a look at it ☺️ 

Thank you!
