### ISSUE TITLE
Missing instruction on how to use polyfill without build system

### ISSUE THREAD

**Issue by jonathan-s** [hotwired/stimulus#321]
I'd like to use the polyfill without a build system. But right now it's missing how to use the polyfill without a build system.

**Comment by loyaruarutoitsu** [comment]
Apparently there isn't. Try creating a buildsystem with gulp, browserify and babelify or see #247

**Comment by dhh** [comment]
Also, we are going to phase out the polyfills as we drop support for IE11.
