### ISSUE TITLE
No error when target or controller is incorrect

### ISSUE THREAD

**Issue by dorner** [hotwired/stimulus#324]
I've had multiple issues where I've tried to set a target on a controller only to mistype or get the name of either the controller or the target wrong. Stimulus happily keeps on trucking without complaining when this happens and I have to debug things. It's even more frustrating when I get the controller name wrong on an action - Stimulus doesn't complain that it can't find the controller, it just does nothing.

I've been enjoying using this quite a bit, but better error checking is a must to improve the development experience.

**Comment by radarek** [comment]
Unfortunately I have the same experience. I was really surprised when I didn't get any error when I misspelled my controller name. I was hoping that maybe it's matter of some error logging configuration but I found that [when module responsible for controller construction isn't found then it's just ignored](https://github.com/hotwired/stimulus/blob/848e0c7d20cec7c6b2d29b10ad3864cae50e645b/packages/%40stimulus/core/src/router.ts#L88-L91).
I think it would desirable to call some error handler there (and default one could just print to the console). Without this people will get upset when they find that they didn't get any error message for misspelled names.
