### ISSUE TITLE
Questions about v2 and dev-builds 

### ISSUE THREAD

**Issue by lidqqq** [hotwired/stimulus#337]
Hey 🦖 

I love StimulusJS!! Cannot wait for v2!!

So, I have a few questions about stimulus [v2](https://github.com/stimulusjs/stimulus/pull/202) and [dev-builds](https://github.com/stimulusjs/dev-builds)

- In dev-builds, `Unifying target attributes` seems like not working since [this dev-build version](https://github.com/stimulusjs/dev-builds/releases/tag/40366c8%2Fstimulus).
  - repl is [here](https://github.com/lidqqq/stimulus-dev-build-test)
- Can we use latest dev-build version? Or should we use [a specific(stable?) version](https://github.com/stimulusjs/stimulus/pull/202#issuecomment-520001308)?
- We try to extend [`Controller.bless`](https://github.com/stimulusjs/stimulus/blob/master/packages/%40stimulus/core/src/controller.ts#L18) for our base application controller making shared utility functions, what do you think about that(this API is maintained in future?)?

**Comment by sstephenson** [comment]
The blessing system will likely change or go away in a future release.
