### ISSUE TITLE
Add previousValue argument to *ValueChanged callback

### ISSUE THREAD

**Issue by dancallaghan** [hotwired/stimulus#346]
At the moment it looks like only the new value is being passed to the value changed callback. It would be quite helpful to have the previous value passed as the second argument, otherwise you have to get/set the previous value against the controller.

It looks like it's possible by passing the [`attributeOldValue`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserverInit/attributeOldValue) option to the mutation observer.

```javascript
loadingValueChanged(newValue, previousValue) {
```

**Comment by dancallaghan** [comment]
Ah, so it looks like the current implementation is passing `get nameValue` as the first argument which handles the type casting. This problem is not as easy as it appears on the surface.

**Comment by dhh** [comment]
If you find a way to do it, please do open a PR for it 👍
