### ISSUE TITLE
Loading controllers from sidecar-style folders

### ISSUE THREAD

**Issue by rrcobb** [hotwired/stimulus#347]
We're using sidecar style folders for [viewcomponent ](https://viewcomponent.org/#sidecar-assets) components. Some components have associated stimulus controllers, for a folder structure like:
```
app/components/multi_photo_uploader
├── component.html.erb
├── component.rb
└── controller.js
```
The `definitionsFromContext` webpack helper expects the controller to have a path and filename that together form the identifier for the controller, but this sidecar naming doesn't work out of the box. I've managed to hack around it and get the controllers loaded manually, but this feels like it might be a conformant naming scheme worth supporting.

In particular, the regex and replace here are tightly bound to the naming scheme in the docs: https://github.com/stimulusjs/stimulus/blob/11370bc37ac07753dbc4d676eebb8534bb03d3f8/packages/%40stimulus/webpack-helpers/src/index.ts#L29 

For others who have this issue, the working-but-notably-less-tested workaround for loading controller definitions from both locations is:

```js 
// app/javascript/controllers/index.js

import { Application } from "stimulus"
import { definitionsFromContext } from "stimulus/webpack-helpers"

const application = Application.start()

// load definitions from app/javascript/controllers
const controllerContext = require.context("controllers", true, /_controller\.js$/)
let controllerDefinitions = definitionsFromContext(controllerContext)

// load definitions from app/components/*
const componentContext = require.context("../../components", true, /.*controller\.js$/)
function getComponentControllerDefinitions(context) {
  return context.keys().map(key => {
    const identifier = key
      .replace("controller.js", "")
      .replace(/[\W_]/g, "-")
      .replace(/^-+/,"")
      .replace(/-+$/, "");
    return { identifier, controllerConstructor: context(key).default }
  })
}
let componentControllerDefinitions = getComponentControllerDefinitions(componentContext);

application.load([...controllerDefinitions, ...componentControllerDefinitions])
```

**Comment by dhh** [comment]
Feel free to submit a PR for the docs that explain this approach of loading from multiple contexts 👍
