### ISSUE TITLE
Incorrect SSL certificate on stimulusjs.org

### ISSUE THREAD

**Issue by ghiculescu** [hotwired/stimulus#356]
Not sure if this is the right place to post this, but since the new magic shipped, the old URLs have this problem:

https://stimulusjs.org/

![image](https://user-images.githubusercontent.com/509837/102915035-c0530d80-4446-11eb-81f8-806c3b392ce1.png)

**Comment by javan** [comment]
Pardon the dust! Should be fixed now (or, whenever the DNS changes propagate your way). ✌️

**Comment by ghiculescu** [comment]
Yep, confirmed for fixed.
