### ISSUE TITLE
static declarations raising an error on safari

### ISSUE THREAD

**Issue by leonardoprg** [hotwired/stimulus#366]
Hello guys,

Im using stimulus 2 with rails pipeline.
All works good except when opening the site on safari (im using safari 14.0.2 on mac and it happens on iphone as well)
which raises an warning `Failed to autoload controller: ...`

Investigating it a bit discovered that the message error is:
`Unexpected token '='. Expected an opening '(' before a method's parameter list`
which is related to the declaration of the target

```
static targets = [ "addressInput" ]
```

removing this line it works well.

any idea how to get it working on safari?

Thanks

**Comment by npezza93** [comment]
In Safari, you can rewrite to:
```js
static get targets() {
  return [ "addressInput" ]
}
```

**Comment by rik** [comment]
More details are available in the [Installation part of the handbook](https://stimulus.hotwire.dev/handbook/installing#using-without-a-build-system).

**Comment by leonardoprg** [comment]
thanks
