### ISSUE TITLE
Convert underscores in data attributes to dashes

### ISSUE THREAD

**Issue by evromalarkey** [hotwired/stimulus#371]
If I want to use underscores in controller name (eg. having unified file name and controller name), data attributes need to have underscores as well, which doesn't look good in the code. Example:

```js
application.register("date_picker", class extends Stimulus.Controller {
    static get values() {
        return {
            date: Object
        }
    }

    connect() {
        console.log(this.dateValue);
    }
});
```

data-date_picker-date-value works
data-date-picker-date-value doesn't work

I guess both is alright, but dashes in data attributes would be preferable. I could also name the controller with dashes, but I want to have same controller name as filename. So some replaceAll conversion at the API level would be nice, maybe only behind optional setting.

**Comment by sstephenson** [comment]
Controller identifiers are always written in kebab-case. From our [Controllers reference documentation](https://stimulus.hotwire.dev/reference/controllers#naming-conventions):

> When an identifier is composed of more than one word, write the words in kebab-case (i.e., by using dashes: date-picker, list-item).

The @stimulus/webpack-helpers package rewrites underscores in controller filenames to dashes automatically to account for this.
