### ISSUE TITLE
package growth 2.0.0 release

### ISSUE THREAD

**Issue by inopinatus** [hotwired/stimulus#374]
The 2.0.0 package includes what I think must be a stray build-time log, and consequently:

```
-rw-r--r--  1 inopinatus  pancakes   11810  8 Jan  2019 stimulus-1.1.1.tgz
-rw-r--r--  1 inopinatus  pancakes  147923  5 Dec 04:20 stimulus-2.0.0.tgz
```

**Comment by javan** [comment]
> what I think must be a stray build-time log

<details><summary>Correct!</summary><img src="https://user-images.githubusercontent.com/5355/107048845-62c91500-6797-11eb-95d4-32442fdbeb17.png" width="600"></details>

Fixed for the next release via https://github.com/hotwired/stimulus/commit/0f6bb92ff2cbf1e22dd1d97b55b96d4a9fc1dcda.
