### ISSUE TITLE
Please keep the old syntax for target attributes

### ISSUE THREAD

**Issue by dbi1** [hotwired/stimulus#376]
Hello Stimulus Team,

Thank you for all the work you put into building Stimulus!

I'm in the process of learning Stimulus, and am finding myself having to think around corners when it comes to the (new) syntax for target attributes.

I just saw examples of the "old" syntax, and it is a breath of fresh air. It's so much easier to write and to think about (at least for me). Maybe others feel this way, too?

In the docs you mention that you are planning to discontinue support for the old syntax. Is there any way you might change your mind?

Thank you very much!

**Comment by gavrichards** [comment]
Hi @dbi1 - I've only just got stuck in with Stimulus, so I'm not familiar with the old syntax at all - can you share where you've seen this? I'm intrigued :)
Thanks

**Comment by dbi1** [comment]
Hi @gavrichards,

I just looked at the [example I saw](https://web-crunch.com/posts/a-tour-of-stimulus-js) again, and the main difference is in how targets and values are referenced. Example for target:

Old version for target:
data-target= "hello.name"

New version for target:
data-hello-target="name"

The more I think about it, the syntax that I would love to use would be yet a bit different from old and new. It would accomplish two things: 

1) Use standard names for data attributes
2) Eliminate the need for referencing the controller name in attributes other than the data-controller attribute. This could be accomplished with a bit of magic by looking at the controller scope in the html within which the data attribute is used.

One example of how this could look like (with a bit of inspiration from alpine.js):

data-target="name"
data-value="{ open: false }"
data-classes="{ loading: 'class1 class2 class 3', loaded: 'class4 class5' }"

Not well addressed in this example is how to work across controllers, this would require some further thought...

**Comment by gavrichards** [comment]
Yes the dot notation namespacing for targets does seem nicer, I wonder why they're moving away from it.
The attributes that I'm finding particularly lengthy are for values.
For example I have some in my project like this:
`data-news--batch-articles-archive-url-value`
where 'news' is a folder, 'batch-articles' is the controller, and 'archive-url' is the name of the variable.

**Comment by Sub-Xaero** [comment]
> 2\. Eliminate the need for referencing the controller name in attributes other than the data-controller attribute. This could be accomplished with a bit of magic by looking at the controller scope in the html within which the data attribute is used.

Stimulus allows you to have multiple controllers attached to an element, and an element can be a target for multiple controllers. The necessity of having the name in the data attributes is to determine when in the scope of multiple controllers - which controller the current target/action/value the attribute should be wired up to. 

The Stimulus core team may correct me, but I believe this was also the intention for the new syntax.
```
<div data-controller="foo bar" data-foo-target="baz bing" data-bar-target="ting tang" /> 
```
makes it easier to see at a glance which targets belong to which controller, and is more DRY than the old syntax: 
```
<div data-controller="foo bar" data-target="foo.baz foo.bing bar.ting bar.tang" /> 
```

The only thing that still uses the dot notation is `actions`.

**Comment by dbi1** [comment]
Thank you @Sub-Xaero, that's a good point... I didn't think about the fact that you can attach multiple controllers to an element... My perspective was single controller elements.

Still, the "little magic" approach to avoid referencing the controller names might work, as the target / value / class names are defined in the static arrays inside each controller's js file.

The problems with this "little magic" approach would be:

1) Data attribute names would have to be unique across controllers
2) The problem of accessing one data controller's attributes inside another is unsolved.

I guess that makes my "little magic" approach not a good apprach...

**Comment by gavrichards** [comment]
It would also mean you'd have to go looking in each relevant controller first to see where the target is referenced, to find out which one is the one that is magically being used.

**Comment by dbi1** [comment]
True... 

Thanks to both of you for helping me think this through.

I'll close this, since I don't have a better idea to propose at this time.
