### ISSUE TITLE
Proposal: Special handling of promise return values for controller actions

### ISSUE THREAD

**Issue by tpetry** [hotwired/stimulus#377]
In case you have defined some actions on an attribute that need to communicate with a server, such as `data-action="server#dosomething thiselement#changesometing notification#showsuccess"` all these actions happen one by one in the stimulus concept. However, in the current implementation of stimulus, the stimulus execution logic has no programmed behavior as to how it should handle the return values of each action. This is not a problem and works great if all actions are of synchronous nature `data-action="focus->field#highlight input->search#update"`.

However, in the former example there is an action `server#dosomething` which is asynchronous. In the current implementation, both other actions are therefore executed immediately, causing changes to the DOM (display success message) before the server has even processed the request.

I would therefore recommend a small change to the current behavior when a Promise is returned by an action:
1. The execution of the next action in the chain waits until the Promise is resolved (`Promise.then`, `Promise.catch`)
2. On successful execution of the action (`Promise.then`) the next action is executed
2. On a failed execution of an action (`Promise.catch`) the chain is aborted.

Possible further (later) extensions could pick up this concept and define actions that are executed when an action failed. This would be possible e.g. by a special syntax like `promise:catch->somecontroller#someaction`.

This small change would enable to make the controllers more generic as intended by stimulus. Because at the moment you have to write specialized controllers all the time if you have async actions and need some things to happen after successfull execution.

**Comment by sstephenson** [comment]
It’s an interesting idea, but unfortunately incompatible with the way DOM events work.

Event dispatch is synchronous. If you call `preventDefault()`, `stopPropagation()`, or `stopImmediatePropagation()` on an event asynchronously, it has no effect.
