### ISSUE TITLE
[Question] Including Vite.js helpers in this monorepo

### ISSUE THREAD

**Issue by ElMassimo** [hotwired/stimulus#378]
Would you accept a pull request to include Vite.js helpers in this repo analogous to the webpack ones?

If not, would you accept a pull request to the docs to mention [`stimulus-vite-helpers`](https://github.com/ElMassimo/stimulus-vite-helpers) so that users can find it more easily?

### Background 📜 

Integrating Stimulus when using Vite.js is simple, but in the same spirit of the `@stimulus/webpack-helpers`, I have created [`stimulus-vite-helpers`](https://github.com/ElMassimo/stimulus-vite-helpers) so that users don't have to copy and paste that code over and over.

As a result, the installation becomes:

```js
import { Application } from 'stimulus'
import { registerControllers } from 'stimulus-vite-helpers'

const application = Application.start()
const controllers = import.meta.globEager('./**/*_controller.js')
registerControllers(application, controllers)
```

**Comment by sstephenson** [comment]
This library looks great! I'm afraid we're not equipped to maintain it in Stimulus core, though. (And in general we're looking to move away from bundler-specific integration and towards plain ES modules.)

How would you feel about starting a community-maintained section or page for other build systems on the [Stimulus wiki](https://github.com/hotwired/stimulus/wiki), and linking to that from the official documentation?

**Comment by ElMassimo** [comment]
Makes perfect sense!

A community-maintained page or wiki would be nice, that way it's easier to keep it up to date.

Let me know if you can make a placeholder, and I'll fill in the rest 😃

Thanks!

**Comment by ElMassimo** [comment]
@sstephenson Quick update, I've added <kbd>[stimulus-vite-helpers](https://github.com/ElMassimo/stimulus-vite-helpers)</kbd> and <kbd>[vite-plugin-stimulus-hmr](https://github.com/ElMassimo/vite-plugin-stimulus-hmr)</kbd> to the [_Controllers and Extensions_](https://github.com/hotwired/stimulus/wiki/Controllers-and-Extensions) page in the wiki.

It would be great to have a link in the _Using Other Build Systems_ section in the [_Installation_](https://stimulus.hotwire.dev/handbook/installing) page.
