### ISSUE TITLE
[Docs] Code snippets don't have line breaks when visiting URL directly

### ISSUE THREAD

**Issue by mattboldt** [hotwired/stimulus#379]
### Description
When I visit this url directly, or land on this page and refresh, the code snippets shift into one line instead of retaining the line breaks. Example url: https://stimulus.hotwire.dev/handbook/working-with-external-resources

However, if I navigate to another link via the left side list, then navigate back (either browser back button or by clicking the link I was on), the code snippets keep their line breaks and everything looks normal. I suspect there's a bug when initializing something via turbolinks navigation.

### Device info
Chrome 88.0.4324.150, macOS 11.2

### Screenshot
![image](https://user-images.githubusercontent.com/1389818/108261925-dd941780-7129-11eb-810b-1473f6a71b1e.png)

**Comment by sstephenson** [comment]
I believe we've fixed this… do the examples look correct to you now?

**Comment by mattboldt** [comment]
Yup, looks good now! 👍
