### ISSUE TITLE
Any plans to support Vite?

### ISSUE THREAD

**Issue by nikolay** [hotwired/stimulus#385]
[Vite](https://vitejs.dev/) uses [Rollup](https://rollupjs.org/guide/en/) for production builds, but it is the fastest for development.

**Comment by arnaudpoullet** [comment]
Hiya,
You should check these out:
[stimulus-vite-helpers](https://github.com/ElMassimo/stimulus-vite-helpers)
[vite-plugin-stimulus-hmr](https://github.com/ElMassimo/vite-plugin-stimulus-hmr)

The author of the plugins actually asked about integration in this repo, which I figure kind of answers your question.
[[Question] Including Vite.js helpers in this monorepo](https://github.com/hotwired/stimulus/issues/378)
