### ISSUE TITLE
Compatibility issues with Datatables.net

### ISSUE THREAD

**Issue by Cartman34** [hotwired/stimulus#387]
Hello,
I am developing a simple controller initializing DataTable (DataTables.net plugin).

It seems this causes the disconnection of the controller, surely because DataTables removed it from the DOM.

So finally, the controller is connected, disconnected, connected and crashes, DataTables rejecting double initialization.

As quick fix, I could only initialize DataTable once checking if this is already done.
But this is not the proper way, this should be done by preventing disconnection.

So, how to do that please ?
Should I use `initialize` method instead ?

**Comment by dancallaghan** [comment]
It’s hard to diagnose the problem without seeing the code, but my guess is that you have a DOM element with a controller that is initialising the datatable using `this.element`.

This might be manipulating the element the controller is attached to and reattaching it to the DOM, causing it to reconnect and initialise the datatable again.

If this is the problem, a possible solution would be to move the controller up the DOM and initialise the datatable using a target.

Something like:

```html
<div data-controller=“datatable”>
  <div data-datatable-target=“table”>
  </div>
</div>
```

```javascript
// Just pseudocode, I don’t know how it is initialised
connect() {
  new Datatable(this.tableTarget);
}
```

**Comment by sstephenson** [comment]
The [community forum](https://discuss.hotwire.dev/) is a great place to post questions like this.
