### ISSUE TITLE
stimulus + vue with slot, the slot name transformed to lower case automatically

### ISSUE THREAD

**Issue by timching** [hotwired/stimulus#389]
Hi, I am using stimulus with vue, but just found that if the slot name is camel case, stimulus will convert all letters to lower case.

follow is the example code snippet that the problem may appear
```HTML
<html>
...
  <div data-controller="example">
  <!-- vue component -->
    <todo>
      <template #subTitle>
        Sub Title
      </template>
    </todo>
  </div>
...
</html>
```

got slot `subtitle` here

----

it all attributes got dasherized?
https://github.com/hotwired/stimulus/blob/c47f551c96f1dc532d98b466d8543e99d1c6decf/packages/%40stimulus/core/src/string_helpers.ts#L9-L11

**Comment by sstephenson** [comment]
Sorry you're having trouble, but this isn't a problem with Stimulus. There's no mechanism in the framework for rewriting attributes in the way you're describing.
