### ISSUE TITLE
Support for custom value types

### ISSUE THREAD

**Issue by trobrock** [hotwired/stimulus#392]
I have multiple stimulus controllers, and suspect a few others have a similar setup that looking something like this:

```javascript
const ACTIVE_CLASSES = ["bg-red-500", "text-white"]
const INACTIVE_CLASSES = ["bg-gray-200", "text-black"]
 
export default class extends Controller {
  enable() {
    this.element.classList.remove(INACTIVE_CLASSES)
    this.element.classList.add(ACTIVE_CLASSES)
  }

  disable() {
    this.element.classList.remove(ACTIVE_CLASSES)
    this.element.classList.add(INACTIVE_CLASSES)
  }
}
```

This works, but what would be great is to be able to keep my class lists in the HTML where I'm doing the rest of my styling. I had thought something like this would be awesome to build:

```javascript
export default class extends Controller {
  static values = {
    activeClasses: ClassList,
    inactiveClasses: ClassList
  }

  enable() {
    this.element.classList.remove(this.inactiveClassesValue)
    this.element.classList.add(this.activeClassesValue)
  }

  disable() {
    this.element.classList.remove(this.activeClassesValue)
    this.element.classList.add(this.inactiveClassesValue)
  }
}
```

```html
<button
    data-controller="button"
    data-button-active-classes-value="bg-red-500 text-white"
    data-button-inactive-classes-value="bg-gray-200 text-black">Click Me</button>
```

I was originally hoping I could build a custom value type to support this, but I don't see how or if that is possible, so I have two questions.

1) Is a custom type possible to build so I could accomplish this?
2) Is this ClassList type something that the community as a whole might find useful?

**Comment by rik** [comment]
If I understood your request, I think [Stimulus already has support for this](https://stimulus.hotwire.dev/reference/css-classes).

**Comment by trobrock** [comment]
@rik I'll have to play with it a bit, but it seems close, though from the docs it doesn't look like it would support a list of classes. In many cases I have a list of 5-8 classes that are logically one set and how I treat them in the controller. This does look like it's probably the better base to build off of though to support a list of classes though.
