### ISSUE TITLE
Alternative to ">" for VIM users?

### ISSUE THREAD

**Issue by pooriar** [hotwired/stimulus#395]
I know this is a _long shot_, but is there any alternative to using the greater than sign `>` in data attributes?

It confuses VIM's built in understanding of tags, making it think that the `>` in the data-action attribute is actually the end `>` of the opening `<button>` tag.
```html
 <button data-action="click->foo#bar"></button>
```

Here's a video showing the same key combination (`citHello` which replaces the inside of an HTML tag with 'Hello') gets confused by the presence of `>` in the attributes

https://user-images.githubusercontent.com/14811629/115944210-057d5f80-a47a-11eb-983d-f07a22b2a362.mp4

Thank you to the maintainers here, stimulus is fantastic ❤️

**Comment by dhh** [comment]
Ah, yeah, that sucks. Hopefully there's a way for the VIM understanding of tag to be made aware of string quotes. Can't and won't change the API for Stimulus on this though.

**Comment by pooriar** [comment]
Fair enough, thanks for the response!

**Comment by luglio7** [comment]
the ">" simbol is a very delicate one in html. It breaks the entire html in kirby cms, it should be customizable.

**Comment by jaredcwhite** [comment]
Can't you use `click&gt;foo#bar` instead? I know it's not pretty but it should fix your syntax highlighting or other parsing issues.
