### ISSUE TITLE
Proposal: Handling multiple classes like targets

### ISSUE THREAD

**Issue by sukei** [hotwired/stimulus#399]
Hello, I'm currently limited by the way Stimulus handle classes and more specifically, multiple classes. 

I'm actually working with TailwindCSS which make extensive usage of utility classes. It is quite hard to manage component representational state with a single class here (due to TailwindCSS utilities classes nature) Stimulus can sure be improved to ease working with multiple classes. I'll illustrate my concern with a simple example:

```html
<div data-tabs-active-class="active">Tab #1</div>
```

```ts
import { Controller } from 'stimulus';

export default class extends Controller {
  static classes = ['active']

  activeClass!: string;

  activeTab(event: Event) {
    (event.currentTarget as HTMLElement).classList.add(this.activeClass);
  }
}
```

So good so far. When the `activeTab` method is invoked, the tab received the `"active"` class. But what if we use the component this way:

```html
<div data-tabs-active-class="bg-blue-200 text-blue-700">Tab #1</div>
```

In such a case, there is an error because `DOMTokenList.add` expects a single token. To fix this, we should do something like this:

```ts
(event.currentTarget as HTMLElement).classList.add(...this.activeClass.split(' '));
```

It make things harder to read and maintain (`split` is not the right thing to do, but you got the point).

Here is my proposal. Add magic properties thats split the tokens and provide them as an array properties like `*Targets` did:

```ts
import { Controller } from 'stimulus';

export default class extends Controller {
  static classes = ['active']

  activeClass!: string;

  activeClasses!: string[];

  activeTab(event: Event) {
    (event.currentTarget as HTMLElement).classList.add(...this.activeClasses);
  }
}
```

WDYT?

**Comment by marcoroth** [comment]
Hey @sukei 👋🏼

You are probably going to like @swanson's merged PR #344

**Comment by sukei** [comment]
Hell yeah! Thanks for this

**Comment by marcoroth** [comment]
@sukei If you would like to make use of it today, you can swap the `stimulus` dependency in your `package.json` to the latest dev-build, like so:
```js
"stimulus": "https://github.com/hotwired/dev-builds/archive/stimulus/848e0c7.tar.gz"
```
