### ISSUE TITLE
Values API seems to be not working with controllers in a folder

### ISSUE THREAD

**Issue by nflorentin** [hotwired/stimulus#406]
Hi,

Let's say that I have a controller "dummy" in a folder named "components" like this:
`webpack/controllers/components/dummy_controller.js`

I referenced my controller in html like this: `data-controller="components--dummy" `, which is perfectly working.

Let's say I declare a value like this:
`  static values = {
    dummyOpt: String
  }`
  
 I do not succeed to get my "dummyOpt" value.
 
 I tried various solutions but none of them seem to work:
 ```html
<div data-controller="components--dummy" data-components--dummy-dummy-opt-value="test"></div>
<div data-controller="components--dummy" data-components-dummy-dummy-opt-value="test"></div>
<div data-controller="components--dummy" data-dummy-dummy-opt-value="test"></div>
```

I just want to know if it is a bug or if I miss something, or if it is simply not implemented at the moment.

Thank!

**Comment by dhh** [comment]
Sounds like a bug. This should work.

**Comment by marcoroth** [comment]
Hey @nflorentin

The first HTML markup works as you think it should work from what I can tell. I've was able to get it working here: https://hotwired-issue-406.glitch.me

Maybe there is something off with how you setup your Stimulus application?

In your case you should have a file named `webpack/controllers/index.js` with the following content:

```js
import { Application } from "stimulus"

const application = Application.start()
const context = require.context("controllers", true, /_controller\.js$/)
application.load(definitionsFromContext(context))
```

Is that right?

**Comment by marcoroth** [comment]
Also: make sure you are actually running Stimulus 2.0.0. 

I was trying to reproduce your case and thought: "yes, looks like something is broken".  I then realized that I'm on Stimulus 1.1.1 😅

**Comment by nflorentin** [comment]
thanks for your reactivity @dhh and @marcoroth 

Oh my god, I'm so ashamed. It works, I had to restart webpack after upgrade.

I'm very sorry for the time you lost with that.
