### ISSUE TITLE
Home page is broken

### ISSUE THREAD

**Issue by ahmad19** [hotwired/stimulus#418]
It seems like an intermittent issue but it errors most of the time. Refer screenshot

<img width="575" alt="Screenshot 2021-07-03 at 12 22 27 AM" src="https://user-images.githubusercontent.com/2041827/124319067-48a13080-db97-11eb-981f-a8c11c0050ff.png">

**Comment by dhh** [comment]
We've moved the site to a new domain to resolve this. Use https://stimulus.hotwired.dev going forward.
