### ISSUE TITLE
Actions not getting triggered for namespaced controllers

### ISSUE THREAD

**Issue by kylazath** [hotwired/stimulus#424]
Let's say i have ```advanced_test_controller.js``` that inherits from ```basic_test_controller.js``` in ```controllers/namespaced``` directory. According to the docs, I should refer to my controller using ```namespaced--advanced-test```. If i specify that whatever controller should trigger ```namespaced--advanced-test#someMethod``` on some action, it won't trigger.

I have tried many other ways to make it work, but still no success. Am I missing something, doing something wrong, or maybe it is not implemented yet?

**Comment by marcoroth** [comment]
Hey @kylazath, what you are describing should work. How does your setup and/or your webpack configuration look like?

I've recreated your case here and that works without an issue:
https://glitch.com/edit/#!/stimulus-issue-424

**Comment by marcoroth** [comment]
Also I just noticed that you are referring to your controller name as `namespaced--avanced-test`, which is missing the `d` in `avanced `

**Comment by kylazath** [comment]
@marcoroth, thanks for your response!
Sorry for this typo, but that was just an example, so it does not really matter.
I am actually using ```hotwire-rails``` with Sprockets, sorry for not mentioning that before, but maybe that is the problem.

**Comment by dhh** [comment]
I can't replicate this either. Please reopen if you can find a way to construct a reproducible example 👍
