### ISSUE TITLE
Debug Mode Output colouring [3.0.0-beta.1]

### ISSUE THREAD

**Issue by leevigraham** [hotwired/stimulus#436]
Overriding debug tools theme to dark mode doesn't update debug console output colours.

In Chrome, Firefox and Safari users can override the system theme (dark, light) just for debug tools.

Chrome: 

<img width="789" alt="image" src="https://user-images.githubusercontent.com/25124/131838924-25e85ca0-7632-4545-8c9f-a4f6e1c5fc96.png">

<img width="786" alt="image" src="https://user-images.githubusercontent.com/25124/131838994-0fdb3f54-51cb-4669-a65e-bb0918039c18.png">

Firefox:

<img width="788" alt="image" src="https://user-images.githubusercontent.com/25124/131839278-b7503921-545a-46ec-9eb3-1569830615c6.png">

<img width="783" alt="image" src="https://user-images.githubusercontent.com/25124/131839326-1cd888c9-603f-46a1-9880-b4a9a0f89597.png">

Safari:

<img width="708" alt="image" src="https://user-images.githubusercontent.com/25124/131839374-443798bc-99f8-4de8-95e8-99d84a88ca03.png">

<img width="708" alt="image" src="https://user-images.githubusercontent.com/25124/131839415-7e24889d-5c90-42e7-b2fe-64c4f4b623f1.png">

**Comment by leevigraham** [comment]
Possible options:

* making the purple a bit brighter
* sticking to one colour that works on both dark and light backgrounds
* Not setting a colour

<img width="225" alt="image" src="https://user-images.githubusercontent.com/25124/131845742-3be05e12-e7d4-45dc-af41-83a9b03518e6.png">

**Comment by dhh** [comment]
We've yanked coloring from rc1 👍
