### ISSUE TITLE
Warnings from nested actions

### ISSUE THREAD

**Issue by michalsznajder** [hotwired/stimulus#441]
I have following structure in HTML with two nested controllers (simplified):

```
<body data-controller="size-publisher">
   <div data-controller="read-more">
      <a data-action="click->read-more#revealMore">more...</a>
   </div>
</body>
```

With 3.0.0.-beta1 I am getting following warnings:

![image](https://user-images.githubusercontent.com/3048239/132001061-a0375ced-c8c6-443a-9655-cf2052774a1f.png)

Later event dispatching work as expected. Looking into code I had feeling that it is connected to this code (no sure where this is located since I use skypack CDN)
```
parseValueForToken(token) {
  const action = Action.forToken(token);
  if (action.identifier == this.identifier) {
    return action;
  }
}
```

`click->read-more#revealMore` is tried to be matched to `size-publisher` but this fails and new warning code kicks in.

**Comment by andre-filho** [comment]
I am having the same problem here. Will this be looked upon?

**Comment by dhh** [comment]
cc @marcoroth

**Comment by marcoroth** [comment]
I will take a look, thanks for the heads up!

**Comment by dhh** [comment]
We're going to revert the warnings system for now. Needs some more time in the oven.
