### ISSUE TITLE
 Question. Did you end ie11 support with v3.0.0-beta1?

### ISSUE THREAD

**Issue by NakajimaTakuya** [hotwired/stimulus#446]
The target of tsconfig seems to have changed from es5 to es2017.
When I look at the PR(#421), it seems to me that this is a deliberate instruction, but does this mean that ie11 is no longer supported?

**Comment by dhh** [comment]
Yes, IE11 support is over with Stimulus 3.0. Documented here: https://github.com/hotwired/stimulus/blob/main/docs/handbook/07_installing_stimulus.md#browser-support

**Comment by NakajimaTakuya** [comment]
Thanks for the reply!
I had missed the documentation.
It's a good time:smile:

**Comment by dhh** [comment]
Added a note about it to https://github.com/hotwired/stimulus/releases/tag/v3.0.0-beta.1 as well.
