### ISSUE TITLE
Add default value to CSS classes values

### ISSUE THREAD

**Issue by leevigraham** [hotwired/stimulus#458]
Values have default values: https://stimulus.hotwired.dev/reference/values#default-values

Is there any reason why the same functionality could not be applied to how classes work?

**Comment by dhh** [comment]
I think that would defeat the purpose a bit. The CSS values are there such that you don't tie your controller source code to your design system. If that's not a consideration, you can just hardcode the css classes you use.

**Comment by janpeterka** [comment]
I understand why this was not implemented.
But I think that this option makes sense, and that the purity of separating design and logic might be counterproductive here.

I will try to explain why I think so:

I'm writing controller that shows remaining character limit for input.
There's default styling that should work in most cases, but as we have many different cases of input, with different layouts, styles and whatnot, it may be necessary, or at least desirable, to style the input a bit.

My best option (in my limited knowledge) is to:
:one: have constant `DEFAULT_CLASSES`
:two: have `indicatorClass`, which is empty most of time
:three: have logic that either uses one of those, or do some merging. Merging would be pretty difficult (we have custom TailwindCSS merger in backend, but rewriting it for controller seems like a bad move), so we stick with doing some `if/else` (most concise way would probably be `this.element.class = this.hasIndicatorClass ? this.indicatorClasses : DEFAULT_CLASSES`)

If this is really the best way to manage this, it's logically equivalent to having defaults for `classes`, with much less code necessary and having defaults together in "statics section".  Also there's an argument for consistency with how values are used. I understand they serve a different purpose, but as a developer, being able to set defaults for `classes` seems intuitive after doing the same for `values`.

I may be utterly wrong here, missing somethings (I'm pretty sure I am), and will be glad for any opposite view improving my undestanding :)

**Comment by adrienpoly** [comment]
I agree I often use the value api just to have access to a default value for CSS classes. 
Also not having the same API between Class and Value is confusing 
We discussed that with @marcoroth and he wanted to make a proposal in that sens.
