### ISSUE TITLE
Blur or Unfocus to a DIV

### ISSUE THREAD

**Issue by francesco-loreti** [hotwired/stimulus#462]
Hi,
Is it possible add the "blur->" or "unfocus->" event?
Or, alternatively, could you tell me how to simulate it? 
I have to apply it to a DIV which has to disappear if I click outside of it.

Thanks,
Francesco

**Comment by asgerb** [comment]
@francesco-loreti there is no such event on a div by default as it does not receive blur. You could add `tabindex="0"` for this, but I think you're really after something like [useClickOutside](https://github.com/stimulus-use/stimulus-use/blob/main/docs/use-click-outside.md) from [stimulus-use](https://github.com/stimulus-use/stimulus-use).

**Comment by francesco-loreti** [comment]
@asgerb It's a very interesting solution. Thanks you.
