### ISSUE TITLE
Controller inheritance using importmap  

### ISSUE THREAD

**Issue by gahia** [hotwired/stimulus#465]
Using stimulus 3.0.0 with importmap, I'm trying:

```js
// application_controller.js
import { Controller } from "@hotwired/stimulus"

export default class extends Controller {
  //...
}
```

```js
// some_controller.js
import { ApplicationController } from "controllers/application_controller";

export default class extends ApplicationController {
  // ...
}
```

FF
`Failed to register controller: some (controllers/some_controller) SyntaxError: import not found: ApplicationController stimulus-importmap-autoloader-7366d931317007a1e7e62c8dd8198dbc6d6b438207ff8d8539d06019597bf2f7.js:24:29
`

Chromium 
`Failed to register controller: some (controllers/some_controller) SyntaxError: The requested module 'controllers/application_controller' does not provide an export named 'ApplicationController'
`

Changing the parent controller to:

```js
// application_controller.js
import { Controller } from "@hotwired/stimulus"

export class ApplicationController extends Controller {
  //...
}
```

`Failed to register controller: application (controllers/application_controller) TypeError: controllerConstructor is undefined`

Not sure is this is a bug on the importmap autoloader or I missing something?

Thanks in advance!

**Comment by gahia** [comment]
Moving this to stimulus-rails...

**Comment by turgs** [comment]
I've got the same issue
