### ISSUE TITLE
[name]Target || Value. Unresolved variable in some IDE

### ISSUE THREAD

**Issue by vastray** [hotwired/stimulus#466]
How to solve the problem of unknown variables in some IDE?
![Снимок экрана от 2021-10-07 11-25-02](https://user-images.githubusercontent.com/51928487/136338746-ea09e138-ca4a-4199-a210-6066e0203ea6.png)
can better declare variables in scope `this` ?

example

```javascript
this.orderQuantity
// or
this.target.orderQuantity
```

**Comment by vastray** [comment]
@Sub-Xaero I am not using a Typescript, but is it possible to do it like this:

```javascript
this.targets.find('name')
// or
this['nameTarget']
```

**Comment by vytant** [comment]
Our team also struggled with this issue and got tired of poor type checking, so we came up with decorators for targets and values. [https://github.com/vytant/stimulus-decorators](https://github.com/vytant/stimulus-decorators)

```typescript
import { Controller } from '@hotwired/stimulus';
import { Value, TypedController, Target } from '@vytant/stimulus-decorators';

@TypedController
export default class extends Controller {
  @Value urlValue!: string;
  @Value methodValue: string = 'GET';

  @Target outputTarget!: HTMLElement;
  @Target errorTarget!: HTMLElement;

  connect() {
    fetch(this.urlValue, { method: this.methodValue })
      .then(response => response.json())
      .then(result => {
        this.outputTarget.textContent = result;
      })
      .catch(error => {
        this.errorTarget.textContent = error;
      });
  }
}
```

All you have to do is define the `*Target` properties and it will add them to the `static targets` array. For `*Value` properties, it takes the type from the type annotation and allows you to assign a default value in a more understandable way.

**Comment by janbaykara** [comment]
> The previous team was working on this topic: https://twitter.com/sstephenson/status/1365863627912339457

What happened to this? Sounds like a successful prototype!

**Comment by calebhearth** [comment]
For posterity, since those links are dead now: https://web.archive.org/web/20210509102149/https://twitter.com/sstephenson/status/1365863627912339457
