### ISSUE TITLE
Incorrect conversion to a Boolean type

### ISSUE THREAD

**Issue by vastray** [hotwired/stimulus#470]
now the boolean value for "Values" is decoded as...
```javascript
return !(value == "0" || value == "false")
```
Some frameworks use logical variables with a capital letter in their templates. (True, False)
In this case: `"False" == "false" // return false`

I suggest converting the parameter to lowercase

```javascript
return !(value == "0" || value.toLowerCase() == "false")
```

**Comment by dhh** [comment]
Do add a PR with tests for this. Agree.
