### ISSUE TITLE
Replacing a controller target w/ a Turbo Stream doesn't trigger target callbacks

### ISSUE THREAD

**Issue by adrianguenter** [hotwired/stimulus#474]
Hi, I have a controller containing a form which returns a Turbo Stream response (as outlined [here](https://github.com/hotwired/turbo/issues/56#issuecomment-753556469)), wherein the response updates an element that is tagged as a controller target. I was hoping that `*TargetDisconnected` and `*TargetConnected` would be called as a result as I need to detect when these elements are replaced, but this doesn't seem to happen.

Is this just not supported or am I doing something wrong? In the meantime I've solved this with my own MutationObserver in the controller, but I'd prefer a built-in solution if it exists.

Thanks!

```
<turbo-frame id="frame" data-controller="foo" data-turbo="true">
    <div id="target" data-foo-target="bar">Old Content</div>
    <form method="post" action="/submit">
         <input type="submit" name="submit"/>
    </form>
</turbo-frame>
```

`submit_response.html`:
```
<turbo-stream action="replace" target="target">
    <template>
        <div id="target" data-foo-target="bar">New Content</div>
    </template>
</turbo-stream>
```

`foo_controller.js`:
```
export default class extends Controller {
    static targets = [
        'bar',
    ]

    connect() {
        console.log('Connect')
    }

    barTargetConnected(element) {
        console.log(element)
    }

    barTargetDisconnected(element) {
        console.log(element)
    }
}
```

**Comment by seanpdoyle** [comment]
I've tried to reproduce this scenario in a test: https://github.com/hotwired/stimulus/compare/seanpdoyle:replace-with-target-callbacks

Without any implementation changes, the test passes. Does that branch re-create your use case?

**Comment by marcoroth** [comment]
Hey @adrianguenter, I just wanted to check back to see if you were able to resolve this issue. And if not, does the test case Sean provided match your use-case?

**Comment by dhh** [comment]
Closing for lack of updates.
