### ISSUE TITLE
API consistency about target and action?

### ISSUE THREAD

**Issue by kud** [hotwired/stimulus#480]
Hello,

I saw that on Stimulus 2, you changed from 

`data-target="[identifier].[name]"`

to

`data-[identifier]-target="[name]"`

Is there a reason you keep

`data-action="[eventListener]->[identifier]#[method]"`

instead of

`data-[identifier]-action="[eventListener]->(#)[method]"`

?

**Comment by kud** [comment]
(and maybe you should open the "discussion" tab not to get feedbacks like this in "issues" 😬)

**Comment by dhh** [comment]
Yes, the order of actions is consequential, so can't use the other style.

There's a discussion forum here: https://discuss.hotwired.dev

**Comment by marcoroth** [comment]
@kud also checkout this issue (#342) for more context.

**Comment by kud** [comment]
Thank you @dhh @marcoroth ! I'll check this issue out. 😌
