### ISSUE TITLE
Make "default" optional in expanded form

### ISSUE THREAD

**Issue by MartkCz** [hotwired/stimulus#487]
```js
static values = {
  id: {
    type: String,
    required: true, // own implementation
  },
  method: String,
};
```

`Type "string" must match the type of the default value. Given default value: "undefined" as "undefined"`

**Comment by marcoroth** [comment]
Hey @MartkCz, thanks for opening this issue!

Are you proposing to add the `required` option to the value definition, that the `default` value option should be optional if you use the expanded form or both?

I think it could make sense to apply both. The `required` option would default to `false`. If you explicitly set it to `true` and don't specify a value or if it doesn't have a default value it will raise with an exception (similar to what we have now).

I'm happy to implement this but I also want to give you the chance to try it yourself if you like.

**Comment by MartkCz** [comment]
The main reason was that default value is required in expanded form. However, it would be great if `required` option will be implemented in library. Unfortunately I don't have enough time right now to send PR :/

**Comment by marcoroth** [comment]
No worries @MartkCz, I will take a look with what I can come up with. Thanks!

**Comment by lucidstack** [comment]
Just adding a 👍 here, as the documentation doesn't make it explicit that the expanded form doesn't work without a default value. Spent an hour thinking I was going crazy until I found this!

**Comment by marcoroth** [comment]
Thanks for the heads-up @lucidstack! 🙌🏼 

I opened https://github.com/hotwired/stimulus/pull/650 to resolve this!
