### ISSUE TITLE
Example error in the handbook

### ISSUE THREAD

**Issue by cerenodeng** [hotwired/stimulus#488]
An error occurs if  following the clipboard example on [step 4 of the handbook](https://stimulus.hotwired.dev/handbook/designing-for-resilience). 

![Screenshot from 2021-11-12 13-29-07](https://user-images.githubusercontent.com/94158380/141415586-d6b68878-8441-484c-8cd6-03030039c4fa.png)

Based on the [CSS Classes of the reference](https://stimulus.hotwired.dev/reference/css-classes), CSS class attributes must be specified on the same element as the data-controller attribute . So that `data-clipboard-supported-class` should be moved into the `clipboard` controller element. The correct example can be
```
<div data-controller="clipboard" data-clipboard-supported-class="clipboard--supported">
    PIN: <input data-clipboard-target="source" type="text" value="3737" readonly>
    <button data-action="clipboard#copy" class="clipboard-button">Copy to Clipboard</button>
</div>
```
not this below
```
<div data-controller="clipboard">
    PIN: <input data-clipboard-target="source" type="text" value="3737" readonly>
    <button data-action="clipboard#copy" class="clipboard-button" data-clipboard-supported-class="clipboard--supported">Copy to Clipboard</button>
</div>
```
Thank you.

**Comment by tleish** [comment]
Good catch.  I suggest posting the issue to https://github.com/hotwired/stimulus-site, and maybe even provide a PR to fix it.

**Comment by cerenodeng** [comment]
Thanks. I didn't know that stimulus-site repository before. I have provided a PR to fix it.
