### ISSUE TITLE
Add function observeMutations

### ISSUE THREAD

**Issue by seb-jean** [hotwired/stimulus#491]
Hi,

Do you think it's interesting to add the default `observeMutations` function in `Controller` class ?

```js
observeMutations(callback, target = this.element, options = { childList: true, subtree: true }) {
  const observer = new MutationObserver(mutations => {
    observer.disconnect()
    Promise.resolve().then(start)
    callback.call(this, mutations)
  })
  function start() {
    if (target.isConnected) observer.observe(target, options)
  }
  start()
}
```

This function comes from the JavaScript code of Hey

**Comment by adrienpoly** [comment]
after some talks the path forward for this feature was mostly decided here https://github.com/hotwired/stimulus/issues/445
