### ISSUE TITLE
[Cross-Controller] Dispatch a custom event returns missing target error

### ISSUE THREAD

**Issue by radinreth** [hotwired/stimulus#492]
Hi there!

I try to coordinate 2 controllers with a custom event.

**scenario:**

I have 2 select boxes reside in 2 different controllers. 

1. change the value from the first select box
2. then, I get an error missing target

<details>

<summary>Stimulus controller</summary>

```js
// controller_a_controller.js
...
myFun() {
this.dispatch("doTask1", { detail: { id: 123 }});
}

// controller_b_controller.js
this.targets = ['myInput'];
...
doTask2() {
  console.log(this.myInputTarget)
}
```
</details>

<details>
<summary>view</summary>

```html
<div data-controller="controller_a controller_b" data-action="controller_a:doTask1->controller_b#doTask2">
  <select data-action="controller_a#myFun"></select>
</div>

<div data-controller="controller_b">
<!-- edited -->
<select data-controller-b-target="myInput"></select>
</div>
```
</details>

**Expected:**
to return **HTML DOM element**

**Actual**
```js
Error invoking action "controller_a:doTask1->controller_b#doTask2"

Error: Missing target element "myInput" for "controller_b" controller
    at extended.get (stimulus.js:2855)
    at extended.doTask2 (controller_b_controller.js:20)
    at Binding.invokeWithEvent (stimulus.js:479)
    at Binding.handleEvent (stimulus.js:449)
    at EventListener.handleEvent (stimulus.js:106)
    at extended.dispatch (stimulus.js:3147)
    at extended.myFun (controller_a_controller.js:18)
    at Binding.invokeWithEvent (stimulus.js:479)
    at Binding.handleEvent (stimulus.js:449)
    at EventListener.handleEvent (stimulus.js:106)

{identifier: 'controller_b', controller: extended, element: div.field-unit, index: 0, event: CustomEvent}
```

**Comment by Sub-Xaero** [comment]
The error is telling you that in ControllerB, you are trying to access a named target `myInput` when you are calling `console.log(myTarget)`, but nowhere in your view do you assign an element to be that target. 

If you want to check if a target exists, you can use `hasMyInputTarget` to check if one has been assigned, and in your view you can assign an element to a target by doing `data-controller-b-target="myInput"`

```
<div data-controller="controller_a controller_b" data-action="controller_a:doTask1->controller_b#doTask2">
  <select data-action="controller_a#myFun" data-controller-b-target="myInput"></select>
</div>
```

**Comment by radinreth** [comment]
@Sub-Xaero thanks for your response, actual `myInput` is already exist `controller_b` and I could see it in console `myInput` as well, the problem happen when I try to dispatch from `controller_a`

**Comment by Sub-Xaero** [comment]
@radinreth  You have two instances of `controller_b`, every time you specify `data-controller='controller_b'` you will get a new instance of that controller scoped to that part of the DOM.  In your edited example, the first instance of `controller_b` i.e. 
```
<div data-controller="controller_a controller_b" ...>
...
</div>
```
does not see the targets of the second instance of `controller_b`. They are two separate objects.

You'll see the error when you dispatch, because your action `controller_a:doTask1->controller_b#doTask2` is calling `controller_b#doTask2` on the `controller_b` it shares an element with, and not the one that actually has the target. 

You need to put `controller_b` on an element higher up in the DOM so that the event can propagate up to it.

```
<div data-controller="controller_b"> 
   <div data-controller="controller_a" data-action="controller_a:doTask1->controller_b#doTask2">
     <select data-action="controller_a#myFun"></select>
  </div>

   <!-- edited -->
  <select data-controller-b-target="myInput"></select>
</div>
```

**Comment by radinreth** [comment]
@Sub-Xaero , that's quite reasonable. 

Let's me try 

Thank you so much  🙏

**Comment by radinreth** [comment]
@Sub-Xaero , I am testing with your first approach

```js
<div data-controller="controller_b"> 
   <div data-controller="controller_a" data-action="controller_a:doTask1->controller_b#doTask2">
     <select data-action="controller_a#myFun"></select>
  </div>

  <select data-controller-b-target="myInput"></select>
</div>
```
but have problem until I lift it up into outside element

```js
<div data-controller="controller_b controller_a" data-action="controller_a:doTask1->controller_b#doTask2"> 
   <div>
     <select data-action="controller_a#myFun"></select>
  </div>

  <select data-controller-b-target="myInput"></select>
</div>
```

**Comment by radinreth** [comment]
I do appreciate for your help @Sub-Xaero
