### ISSUE TITLE
Standard Html in data-action

### ISSUE THREAD

**Issue by luglio7** [hotwired/stimulus#498]
I'm building a website in Wordpress. Gutenberg escape everything after the ">" symbol (which should not be used in html attributes), and i'm unable to use Stimulus for any Wordpress related project.

Please change or add a simple way to customize the pattern "event->controller#method".

<img width="811" alt="Schermata 2021-12-10 alle 16 47 53" src="https://user-images.githubusercontent.com/6023581/145604198-f03ae063-6c87-4df0-9543-59c402b82c63.png">

**Comment by dhh** [comment]
That's unfortunate, but not something we're going to change. Gutenberg can probably be updated such that the escape regexp deals with the fact that > is a legal character inside a quoted attribute.

**Comment by luglio7** [comment]
I leavew this note here for Wp Gutenberg devs.
In wordpress blocks use this pattern to define actions: "event.controller#method"

then add this filter to bypass escaping.

```
// content after escaping
add_filter("the_content", function ($content) {
  $content = preg_replace('/data-action\=\"(.+?)\.(.+?)"/', 'data-action="$1->$2"', $content);
  return $content;
}, 11);
```
