### ISSUE TITLE
Multi event actions

### ISSUE THREAD

**Issue by dvisockas** [hotwired/stimulus#500]
Hey,

In one of my apps I had a problem that I needed few events to trigger the same input action.
It looked like `paste->changeThings input->changeThings`.

I think it would be nice to have a map between multiple events and an action like `paste,input->changeThings`.

Would this make sense as an addition to stimulus?

**Comment by stillhart** [comment]
I just run into a similar issue. I couldn't find any mention in the docs on how to allow for multiple actions, but actually you can just space them.

```html
<input type="text" data-action="keyup->controller#method change->controller#method">
```

I propose to add an equivalent of [this vuejs example](https://vuejs.org/v2/guide/#Handling-User-Input) to the docs. I think it would nicely show how everything interacts, how to handle multiple events, how to fill them back into the UI and more. It was one of my favorite examples of vuejs.
```html
<div id="app-6">
  <p>{{ message }}</p>
  <input v-model="message">
</div>
<script>
var app6 = new Vue({
  el: '#app-6',
  data: {
    message: 'Hello Vue!'
  }
</script>
})
```

**Comment by dvisockas** [comment]
@stillhart the issue is not multiple actions, but rather multiple event trigger mapping to a single controller action

**Comment by kieraneglin** [comment]
+1 for this.  We have a controller that needs to run the same action on change, keyup, blur, and focus.  As-is, it's pretty cumbersome to handle all these cases.

**Comment by rik** [comment]
>  I couldn't find any mention in the docs on how to allow for multiple actions, but actually you can just space them.

https://stimulus.hotwired.dev/reference/actions#multiple-actions

---

I don't think the complexity of implementing multi event-type in the framework and explaining the new syntax in the docs is worth the value for the few times when you need to listen to several event types with the same action.

In the three examples given, it seems to me that using the [default event type for input elements](https://stimulus.hotwired.dev/reference/actions#event-shorthand) (aka `input`) would probably cover all cases (paste, change, keyup, blur and focus).

**Comment by kieraneglin** [comment]
Thanks for the tip!  `input` does work to replace some of the events, but it doesn't cover `blur` and `focus`.  This isn't the end of the world, but it can become very cumbersome and repetitive if you have actions from multiple controllers each listening for multiple events.

**Comment by dhh** [comment]
Appreciate the point. We'd discussed this in the past. Conclusion was the same as @rik. The savings weren't worth the added complexity.

**Comment by frayzil** [comment]
Hey @dvisockas @stillhart @kieraneglin 

If you're still interested in a solution, there are two ways to achieve it. The core idea is to **mix the events create a custom event and dispatch it** to the element.

# Method 1: Use a helper to mix events in the controller
https://jsfiddle.net/frayzil/1ebfmgk7/8/

## The HTML
```html
<div data-controller="test">

  <input
    data-action="input,focus,blur->test#test"
    data-test-target="one">

  <input
    data-action="input,focus->test#test"
    data-test-target="two">

  <p data-test-target="output"></p>
</div>
```

## The Controller
```js
// controllers/test_controller.js
import mixEvents from 'helpers/mix_events'

export default class extends Controller {

  static targets = [ "one", "two", "output" ]

  connect() {
    mixEvents(this.oneTarget, ["input", "focus", "blur"])
    mixEvents(this.twoTarget, ["input", "focus"])
  }

  test() { ... }

}
```

## The Helper
```js
// helpers/mix_events.js
export const mixEvents = element, ingredients => {
  const mixedEvent = new Event(ingredients.join(','))

  ingredients.forEach(listenAndDispatch)

  function listenAndDispatch(ingredient) {
    element.addEventListener(ingredient, dispatchMixedEvent)
  }

  function dispatchMixedEvent(event) {
    event.target.dispatchEvent(mixedEvent)
  }

}
```

# 2. Use a controller to mix events in the HTML
https://jsfiddle.net/frayzil/1ebfmgk7/13/

## The HTML
```html
<div data-controller="test">

  <input
    data-controller="events-mixer"
    data-events-mixer-ingredients-value="input,focus,blur"
    
    data-action="input,focus,blur->test#test"
    data-test-target="one">

  <input
    data-controller="events-mixer"
    data-events-mixer-ingredients-value="input,focus"
    
    data-action="input,focus->test#test"
    data-test-target="two">

  <p data-test-target="output"></p>
</div>
```

## The EventsMixerController
```js
export default class extends Controller {

  static values = {
    ingredients: String
  }

  connect() {
    mixEvents(this.element, this.ingredientsValue.split(','))
  }

}
```
