### ISSUE TITLE
How to fix a warning when attaching stimulus target to a rails helper

### ISSUE THREAD

**Issue by malinowskil123** [hotwired/stimulus#506]
Warning browser console
![Screen Shot 2022-01-18 at 11 48 03 AM](https://user-images.githubusercontent.com/48255282/149981256-8552600b-60b6-42fb-8a42-58986a2fcf15.png)

current code 
```ruby
 <%= image_tag "logo.png",  data: { target: "file-input.image" } %>
```

I couldn't find any docs on explaining the new syntax on hooking up targets to rails helpers.
I've tried to follow the html example but it didn't work 

```ruby
 <%= image_tag "logo.png", data: { target: "file-input-image" } %>
```

Any help is appreciated.

**Comment by dhh** [comment]
<%= image_tag "logo.png", data: { file_input_target: "image" } %>
