### ISSUE TITLE
document additional options for this.dispatch

### ISSUE THREAD

**Issue by lb-** [hotwired/stimulus#510]
I have noticed in the code that `this.dispatch` on a controller allows extra options, specifically a `target` for dispatching an event on a custom target. 

https://github.com/hotwired/stimulus/blob/53189b473651e7288845af88fef661be69f27345/src/core/controller.ts#L64

However, this is not listed in the official documentation

https://stimulus.hotwired.dev/reference/controllers#cross-controller-coordination-with-events

Proposed solution; document the `target` option and other options supported; `prefix`, `cancelable` and `bubbles`. 

I understand if prefix is something that should not be documented as the consistent event naming is one of the good things about using `this.dispatch`. 

I would be happy to submit a docs PR if this is something useful.

**Comment by hms** [comment]
This would be helpful

**Comment by dhh** [comment]
Please do 👍
