### ISSUE TITLE
Q: Can we execute some JS inline in HTML?

### ISSUE THREAD

**Issue by igorkasyanchuk** [hotwired/stimulus#511]
If we have code something like:
![image](https://user-images.githubusercontent.com/11101/152168007-254cc89a-a161-4f3d-926c-44a814c9f5a3.png)

Can we simplify it and do something without adding any JS file (pay attention to the button data-action):

```html
<div data-controller="hello">
  <input data-target="hello.name" type="text">

<!-- THIS IS IMPORTANT LINE  !!!!! -->
  <button data-action="click->hello###this.outputTarget.textContent =`Hello, ${this.nameTarget.value}!`"> 
<!-- ------- -->
    Greet
  </button>

  <span data-target="hello.output">
  </span>
</div>
```

I think it could be a nice feature and let us avoid making many small JS files.

**Comment by Sub-Xaero** [comment]
You probably want something more like https://alpinejs.dev/ 

Also, that is bad security practice IMHO. Both Alpine and what you suggested relies on `unsafe-eval` being allowed, and very loose CSP policies.

**Comment by igorkasyanchuk** [comment]
yes, was thinking about Alpine.js as an example. Okay, from the security point of view it makes sense.
Closing ticket :)
