### ISSUE TITLE
Stimulus is swallowing exceptions?

### ISSUE THREAD

**Issue by phuongnd08** [hotwired/stimulus#512]
I create a controller definition like this one:

```
import { Controller } from "@hotwired/stimulus"

export default class extends Controller {
  static targets = ["signaledAt", "video"]

  step = 1.0/25

  nextFrame(event) {
    event.preventDefault()
    this.videoTarget.currentTime += this.step;
    if (this.videoTarget.currentTime > this.videoTarget.duration)
      this.videoTarget.currentTime = this.videoTarget.duration;
  }

  prevFrame(event) {
    event.preventDefault()
    this.videoTarget.currentTime -= this.step;
    if (this.videoTarget.currentTime < 0)
      this.videoTarget.currentTime = 0;
  }

  frameUpdated(event) {
    this.signaledAtTarget.value = this.videoTarget.currentTime;
  }

  videoLoaded(event) {
    this.videoTarget.currentTime = this.signaledAtTarget.value
  }
}
```

If I insert a bogus syntax as the end of the file, like:
```
randomlyNonExistentMethod();
```

it's supposed to log an exception to chrome dev tools, but it currently not. Instead, it swallows the exceptions make it tricky for dev to identify error. Please advice.

**Comment by rupasix** [comment]
It probably depends on your build tool. I tested your code using webpack and babel and in FE i get `undefined function`. You would have to describe how you build your JS file if you need more help.

**Comment by phuongnd08** [comment]
Then i guess it's rails config. I'm using stimulus in a fresh rails 7 app

**Comment by lb-** [comment]
Not sure on errors outside of your Controller class, but maybe debugging mode is worth a go. 

https://stimulus.hotwired.dev/handbook/installing#debugging

**Comment by dhh** [comment]
We're limited to the debugging provided by the browsers when using import maps.
