### ISSUE TITLE
Suggestion - allow for a Application wide (schema) base prefix on dispatch 

### ISSUE THREAD

**Issue by lb-** [hotwired/stimulus#519]
I'd like to suggest that there be a supported approach to allow for an additional base prefix on dispatching events to be dictated at the schema. 

Currently the data attributes can be customised - as per the documentation
https://stimulus.hotwired.dev/handbook/installing#overriding-attribute-defaults

However, the dispatch on controllers does not allow for a custom base prefix to be added to all events. 

https://github.com/hotwired/stimulus/blob/f10762be6cc58facc5cac66b9f4a5384779f3afd/src/core/controller.ts#L65

The use case is similar to the data attributes schema where Stimulus may want to be used alongside other Stimulus usages. 

If two modal implementations exist with the identifier `modal` and need to interact by events, and they both dispatch `open` it will not be practical to differentiate these. 

If there was a base prefix. One library could use `tw` which would create the event `tw:modal:open` and another could use a base prefix of `bs` (or none) to dispatch the event as `bs:modal:open`. 

This could of course be implemented as a custom base Controller that all other controllers extend but it would be great to see this in the library in some form. 

I'm happy to submit a PR with tests if there is an appetite for this. 

Rough implementation 
```js

dispatch(eventName: string, { target = this.element, detail = {}, basePrefix = this.application.schema.eventBasePrefix, this.prefix = this.identifier, bubbles = true, cancelable = true } = {}) { 
   // The eventName is converted to a string to preserve previous behaviour if undefined or null for some reason
    const type = [basePrefix, prefix, `${eventName}`].filter(value => value).join(':')
    const event = new CustomEvent(type, { detail, bubbles, cancelable })
    target.dispatchEvent(event)
    return event
  }

```

**Comment by marcoroth** [comment]
Hey @lb-, thanks for opening this issue!

I understand the technical implementation of what you are proposing, though I'm not sure I follow how this is useful in applications. 

Stimulus is designed to be used with a single Stimulus `Application` instance. This is also the case if you have two libraries providing `modal` implementations. Since the controllers of those libraries get registered into the applications Stimulus `Application` it would have no effect to have a global prefix. 

Or am I misunderstanding something here?

**Comment by lb-** [comment]
Based on the Stimulus schema architecture - I would assume that it has been designed to allow for multiple applications. You can define completely different data attribute naming conventions per schema.

But, irrespective of that use case, I think it would be valuable to be able to define the base prefix of all event names that come from an application's dispatch method.

An example of how we may use this in Wagtail is we currently prefix all events with Wagtail so that an event might be  `wagtail:modal:open`.

To preserve this consistent behaviour we would have to call dispatch with the prefix 'wagtail' and the controller's identifier 'modal' manually. 

We could probably provide a base controller that overrides the dispatch method and all other controllers extend that.

**Comment by marcoroth** [comment]
> Based on the Stimulus schema architecture - I would assume that it has been designed to allow for multiple applications.

You are right. I guess what I wanted to say is "Usually you are using Stimulus with a single Application instance".

Given the schema holds the names for the data attributes, does it make sense to have the global prefix as part of that same schema? 

Personally I don't have a strong opinion about whether Stimulus should support it or not. But either way, to me this seems like a very unusual edge case. Luckily it can be "solved" fairly straightforward on the application level with a general `ApplicationController` or `BaseController` which overrides the `dispatch` function.

I'd be interested to know how others feels about this and if they would want this as part of Stimulus.

**Comment by lb-** [comment]
Thanks @marcoroth - I appreciate the thoughtful feedback.

Happy for this to be closed if there is not really a shared need for this.
