### ISSUE TITLE
Easily upgrade deprecated target syntax in views

### ISSUE THREAD

**Issue by jamesmacwilliam** [hotwired/stimulus#526]
less of a request and more of a share, I didn't see an upgrade tool to upgrade the deprecated data-target="controllername.targetname" to data-controllername-target="targetname" syntax so I wrote a quick rake task for anyone else who needs to upgrade:

`bundle exec rake stimulus:upgrade`

```
namespace :stimulus do
  desc "upgrade target syntax"
  task :upgrade do
    Dir["app/views/**/**/*.*"].each do |path|
      orig = File.read(path)
      str = orig
        .gsub(/target[:] ["']([-a-z]*)[.]([-a-z]*)["']/, '"\1-target": "\2"')
        .gsub(/data-target=['"]([-a-z]*)[.]([-a-z]*)['"]/, 'data-\1-target="\2"')
      File.open(path, "w") { |f| f.puts str } unless orig == str
    end
  end
end
```

**Comment by marcoroth** [comment]
@jamesmacwilliam nice! It might make sense to contribute this Rake task to `stimulus-rails` since it's Rails specific
