### ISSUE TITLE
Support for some other Action Options and Key Modifiers would be great

### ISSUE THREAD

**Issue by radiantshaw** [hotwired/stimulus#530]
This issue is inspired by #440, #442, and [Vue's `v-on` directive](https://vuejs.org/api/built-in-directives.html#v-on). Out of the listed "Modifiers", Stimulus already has the following:

- `:capture`
- `:once`
- `:passive`
- `:!passive`

The `.{keyAlias}` Key Modifier is already being handled in #442 for keyboard events. We can have the equivalent `.left`, `.right`, and `.middle` Key Modifiers for mouse events as well.

On top of that, seems like having a `:self` Action Option would be great. Maybe an equivalent `:!self` as well?

And I know that the `:stop` and `:prevent` Action Options aren't necessary since the same can be done inside the handler itself, but it'd be nice to have those options as well to reduce `event.stopPropagation()` and `event.preventDefault()` inside most handlers.

Thoughts?

**Comment by dhh** [comment]
Yeah, I fundamentally like this syntax, and would happy to see it extended to mouse clicks as well. Do investigate.

**Comment by radiantshaw** [comment]
@dhh Sure. I'll take this up and raise an appropriate PR for it. Thanks! 🤝

**Comment by adrienpoly** [comment]
I like this idea for `:stop` `:prevent`

I suppose we would be able to chain them ?
```html
<div data-action="click->controller#vote:once:prevent">
```

**Comment by dhh** [comment]
Ahh, I had thought of click.once->controller, but what you're proposing is even better, @adrienpoly. And yeah, the chaining seems very reasonable. Should still combine this with @NakajimaTakuya's work on the hotkeys and mouse modifiers, so we could have `click.left->controller#vote:once`.

**Comment by adrienpoly** [comment]
yes `click.once->controller` was this initial syntax when we looked into this action options feature (https://github.com/hotwired/stimulus/pull/232) but we ended up with `click->controller#action:once` 

So we would :
- describe event **options** with trailing `:option` tokens
- **filter** events with `.variation` token (probably only one in this case)

## Examples

```html
# mixing event variant and event options
<div data-action="click.left->controller#vote:once:prevent">

# with global listener
<div data-action="keydown.left@window->tabs#prevTab">

```

**Comment by radiantshaw** [comment]
Just an update. I'm also implementing the `:self` functionality in a [separate branch](https://github.com/radiantshaw/stimulus/tree/self-and-not-self-action-options) in my fork. But I'm waiting for #535 to get approved and merged first.
