### ISSUE TITLE
Native support for transitions

### ISSUE THREAD

**Issue by DaniG2k** [hotwired/stimulus#542]
I was having a look at the [Tailwind documentation](https://tailwindui.com/components/application-ui/elements/dropdowns) and saw that some of their components have inbuilt support for transitions in Vue and React, but if one checks the pure HTML version they only indicate which transition points to use.

I was a bit stumped as to how to replicate this with Stimulus until I came across [this article](https://dev.to/mmccall10/tailwind-enter-leave-transition-effects-with-stimulus-js-5hl7). The author built a small package called [el-transition](https://github.com/mmccall10/el-transition) that adds the necessary animation frames to make this work with Stimulus.

While this solution works nicely, I was wondering if it wouldn't be worth adding something as basic as transitions to the core Stimulus framework? I was a little disappointed to see it's not inbuilt.

Thanks and apologies in advance if this kind of question is not in line with the community guidelines 🙏🏻 🙏🏻

**Comment by dhh** [comment]
This is something that would be nice to have in a Stimulus standard library. Not something I think is a good fit for core. Good first step to exploring it is simply building it as a separate package, like stimulus-transitions, and validating API and fit from there. Please do investigate 👍
