### ISSUE TITLE
Add ability to ignore a section of DOM 

### ISSUE THREAD

**Issue by lb-** [hotwired/stimulus#545]
## Problem

- When Stimulus is active on the page it will automatically trigger for any elements in the DOM whenever they get added which is great. 
- However, there are some cases where we may not want this to happen such as the user having control over some data attribute modification via user entry or showing a section of content line a preview that may inadvertently render uncontrolled data attributes. 

## Proposal

- provide a data attribute or config to make it possible for a branch of DOM to be skipped by any controllers. 

## Potential Implementation Ideas

- add a new attribute such as `data-controller-ignore` which will cause any controllers within that Dom element to not be connected. This attribute should be able to be modified in the schema. 
- add an application config that provides a function to be called before a class is instantiated against a Dom element with that Dom element or even just a selector passed into matches.  `window.Stimulus = Application.start(document.documentElement, {ignoreMatches '[data-ignore]'});`

## Similar concepts
- htmx has `hx-disable` https://htmx.org/docs/#security
- alpine js has `x-ignore` https://alpinejs.dev/directives/ignore

## Alternative work arounds

- provide an extended application or base controller that somehow hooks into similar behaviour as `shouldLoad` to be given a function with the element attempting to be connected to and add ability to disqualify it via a selector. 
- https://stimulus.hotwired.dev/reference/controllers#preventing-registration-based-on-environmental-factors
- https://developer.mozilla.org/en-US/docs/Web/API/Element/matches - could be used.

**Comment by dhh** [comment]
Seems you're better off treating user-data HTML as something that needs to be sanitized. Rather than sandbox stimulus invocation. Switch to using an allow-list of attributes for user-data.

**Comment by lb-** [comment]
No problems, I agree with that approach but thought I would see if there was an appetite to add this functionality.
Thanks for the response.
