### ISSUE TITLE
multiple connect() calls for same element?

### ISSUE THREAD

**Issue by mockdeep** [hotwired/stimulus#549]
We're running into an issue have a controller that very occasionally connects twice on the page. There is only one element that could be connected, but we rarely get reports that it has been connected twice. The way we know it's getting connected twice is that we add a keyed `beforeunload` event listener on the page, and we report to our an error tracker when the key gets added twice.

We don't have Turbo enabled on the page, and it's a very small percentage of requests that triggers the issue. Most of the reports are from Mobile Safari, though we've also seen it on Chrome and Edge on Windows. It's a little concerning, though, since this controller has a lot of legacy logic that might not gracefully handle being called twice.

Is there any weird browser that could cause an element to come into the page twice? All of the HTML is static server rendered.

**Comment by dhh** [comment]
Haven't heard of this problem, but generally speaking, you should design your controllers to be idempotent. Stimulus was designed for elements that trigger controllers to be added and removed.
