### ISSUE TITLE
turbo-stream replacing target results in stale target

### ISSUE THREAD

**Issue by Bumppoman** [hotwired/stimulus#550]
Hi,

Given the following HTML:

```
<div data-controller="foo">
    <div id="bar" data-foo-target="bar">Hello</div>
</div>
```

and the following Stimulus controller:

```
import { get } from '@rails/request.js';

export default class extends Controller {
    static targets = ['bar'];

    connect () {
        get('http://foobar.com', { responseKind: 'turbo-stream' })
            .then(() => console.log(this.barTarget));
    }
}
```

The console output will be the stale element that is being replaced.  This seems to be the case even if I explicitly wait for some of the content to be in the DOM (chaining another `Promise.then` containing a MutationObserver).

This has crippled my use of targets.  I've had to resort to `document.getElementById` (which works perfectly as a drop-in replacement in the above code).  Have I done something wrong?  Is there a way to do this?

**Comment by seanpdoyle** [comment]
@Bumppoman thank you for opening this issue.

Is it possible that `get`-generated Promie is resolving too early?

Have you considered [opening an issue against `rails/request.js`](https://github.com/rails/request.js/issues/new)?

I don't have much first-hand experience with using that package, but my hunch is that timing issues might be related to [`FetchResponse.renderTurboStream`](https://github.com/rails/request.js/blob/a2d1ae443fdd9dae69e660c10e5724691c2155df/src/fetch_response.js#L64-L74).

**Comment by Bumppoman** [comment]
@seanpdoyle I definitely think the `get` Promise resolves immediately when the response is received and not when it's applied.  However, I rigged up the following to theoretically combat that:

```
  waitForElement (selector) {
    return new Promise(
      resolve => {
        if (document.querySelector(selector)) {
          return resolve(document.querySelector(selector));
        }

        const observer = new MutationObserver(
          () => {
            if (document.querySelector(selector)) {
              resolve(document.querySelector(selector));
              observer.disconnect();
            }
          }
        );

        observer.observe(document.body, { childList: true, subtree: true });
      }
    
```

I then chained that onto the above and waited for an element that is only available in the turbo-stream update:

```
import { get } from '@rails/request.js';

export default class extends Controller {
    static targets = ['bar'];

    connect () {
        get('http://foobar.com', { responseKind: 'turbo-stream' })
            .then(() => this.waitForElement('#only-in-turbo-stream'))
            .then(() => console.log(this.barTarget));
    }
}
```

Still getting the same result.

**Comment by seanpdoyle** [comment]
@Bumppoman thank you for the additional context, and for sharing the `waitForElement()` helper.

Could you share an example of a `<turbo-stream>` response that you're experimenting with?

**Comment by seanpdoyle** [comment]
The [`this.[name]Target` generated property](https://github.com/hotwired/stimulus/blob/1cfa85c2c8abdd969ee56509cc2e0aadc42af0d2/src/core/target_properties.ts#L15-L24) (along with its internal calls to [`TargetSet.find`](https://github.com/hotwired/stimulus/blob/1cfa85c2c8abdd969ee56509cc2e0aadc42af0d2/src/core/target_set.ts#L27-L33), [`TargetSet.findTarget`](https://github.com/hotwired/stimulus/blob/1cfa85c2c8abdd969ee56509cc2e0aadc42af0d2/src/core/target_set.ts#L43-L46), and [`Scope.findElement`](https://github.com/hotwired/stimulus/blob/1cfa85c2c8abdd969ee56509cc2e0aadc42af0d2/src/core/scope.ts#L25-L29)) traverse the document synchronously each time, without any kind of memoization or caching. I'm surprised your example is exhibiting this behavior.

To further troubleshoot, could you declare [`barTargetConnected()` and `barTargetDisconnected()` Lifecycle hooks](https://stimulus.hotwired.dev/reference/targets#connected-and-disconnected-callbacks) with `debugger` statements, replace the `console.log(this.barTarget)` with a `debugger`, then step through them to sequentially to determine the order they're evaluated?

I'd expect something like the following:

1. the `barTargetConnected()` hook is invoked with the original element as its `target` argument
2. the `barTargetDisconnected()` hook is invoked with the original element (in its detached state) as its `target` argument
3. the `barTargetConnected()` hook is invoked with the new element
4. the `get`-generated Promise is invoked with the new element accessible through `this.barTarget`

**Comment by dhh** [comment]
Closing for lack of updates.
