### ISSUE TITLE
Do you plan to introduce OUTLET?

### ISSUE THREAD

**Issue by NakajimaTakuya** [hotwired/stimulus#552]
I know that hey has created a property called outlet as a means of using controllers.

`data-{controller}-{outlet_controller_name}-outlet="{reference_id}"`
https://github.com/hotwired/stimulus/issues/35#issuecomment-355311491

I sometimes find this outlet useful in cases where the coordination between controllers cannot be resolved by events alone.
Now I am like hey and have defined an outlet using `blessings`, will this ever be officially introduced?
Or is there room for consideration if I create that PR?

**Comment by dhh** [comment]
Yes via #576 👍

**Comment by NakajimaTakuya** [comment]
Thank you. Today is a great day.
