### ISSUE TITLE
Action params not passed when event is load@window, working otherwhise?

### ISSUE THREAD

**Issue by gremo** [hotwired/stimulus#556]
Am I'm missing something from the documentation?

```html
<a data-controller="test"
  data-action="load@window->test#foo mouseover->test#foo"
  data-test-bar-param="baz">
  Hello World!
</a>
```

When `load@window` event  params is an empty object. When `mouseover` it's ok `{ bar: "baz" }`.

```js
// test_controller.js
import { Controller } from '@hotwired/stimulus';

export default class extends Controller {
  foo({ params }) {
    console.log(params);
  }
}
```

**Comment by rupasix** [comment]
Probably window load event happened before your controller wiring with HTML.

**Comment by lb-** [comment]
If you want to listen to an event as early as possible you can try  `readystatechange` https://developer.mozilla.org/en-US/docs/Web/API/Document/readystatechange_event

**Comment by gremo** [comment]
@rupasix 

> The load event is fired when the whole page has loaded, including all dependent resources such as stylesheets and images. 

Exactly what I need/want.

**Comment by gremo** [comment]
@adrienpoly will be released soon? Thanks, closing this

**Comment by gremo** [comment]
@adrienpoly any update about the new release? We really need this feature!
