### ISSUE TITLE
Action parameters do not work if the controller name is camelCase

### ISSUE THREAD

**Issue by asprega** [hotwired/stimulus#558]
In case the controller identifier has any capital letter in it, parameters are not picked up because the RegExp to match them is case sensitive, and in the dom attribute names get all flattened to lowercase.

```
class Action {
    ...
    getParamsFromEventTargetAttributes(eventTarget) {
        const params = {};
        const pattern = new RegExp(`^data-${this.identifier}-(.+)-param$`); // This fails to pickup parameters in case of camelCase controllers
        const attributes = Array.from(eventTarget.attributes);
        attributes.forEach(({ name, value }) => {
            const match = name.match(pattern);
            const key = match && match[1];
            if (key) {
                Object.assign(params, { [camelize(key)]: typecast(value) });
            }
        });
        return params;
    }
```

Even though it doesn't seem to be a suggested practice from the doc, it should still be possible to use camel case for controller names. Would it be acceptable making the regexp case insensitive, so that parameters are matched regardless? If so, I can send a pull request.

**Comment by tleish** [comment]
I may be misunderstanding the question, but here's one answer.

> Even though it doesn't seem to be a suggested practice from the doc, it should still be possible to use camel case for controller names. 

The documentation does [specify naming conventions](https://stimulus.hotwired.dev/reference/controllers#naming-conventions).   This naming convention follows the [standard HTML naming conventions for data attributes](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset#name_conversion), which uses kebab-case (or dash-case) for html attributes.  Browsers javascript converts to kebab-case to camelCase for variables, and the reverse.

#### HTML kebab-case to Javascript camelCase

```html
<div id="my-element" data-my-attributes="true/>
```
becomes javascript camelCase
```javascript
document.getElementById('my-element').dataset.myAtrribute; // true
```

More importantly, the opposite is true.  Browsers convert Javascript camelCase to kebab-case.

#### Javascript camelCase to HTML kebab-case

```javascript
document.getElementById('my-element').dataset.myAtrribute = true
```
becomes HTML kebab-case
```html
<div id="my-element" data-my-attributes="true/>
```

This is why stimulus documentation specifies use kebab-case in HTML

```html
<div id="my-element" data-action="my-controller" data-my-controller-value="true/>
```
