### ISSUE TITLE
Action parameters do not work if the controller identifier has any capital letter in it

### ISSUE THREAD

**Issue by asprega** [hotwired/stimulus#561]
Hi Stimulus team, and thanks for your amazing work.

Sorry for not having replied on time, but referring to my previous issue: https://github.com/hotwired/stimulus/issues/558 I think I did not explain clearly my problem, so I will try to do it now.

Problem: when the controller identifier has any capital letter in it, params are not passed to the triggered action.

This is a code snippet that reproduces the issue:
```
<html>
<head>
  <script type="module">
    import { Application, Controller } from "https://cdn.skypack.dev/@hotwired/stimulus@3.0.1";

    const application = Application.start();

    class CamelCaseController extends Controller {
        action(event) {
            alert(event.params.foo); // Opens alert with `undefined`
        }
    };

    application.register("CamelCase", CamelCaseController);
  </script>
</head>
<body>
 <div data-controller="CamelCase">
   <button data-action="CamelCase#action"
        data-CamelCase-foo-param="bar">
     Open alert
   </button>
 </div>
</body>
</html>
```

The result is that `undefined` is printed, even though the parameter `foo` should have value `bar`

If you change the controller name to `camelcase`, thus removing capital letters both in html and js, things will work as documented.

I believe this is an issue because other features of the framework (i.e. targets and values) work even when the controller identifier is not all lowercase.

If you confirm this is something to be fixed, I can open a PR for this.

Thanks!

**Comment by adrienpoly** [comment]
I agree that it should be consistent either fully support or not . Since this was the original behavior for other attributes, we should update the params API with that case insensitive regex. 
This being said, I don't think this should be documented

**Comment by PauchardThomas** [comment]
I got the issue with a folder inside controllers : 

* assets/controllers/adminArea/orders_controller.js -> params not working
* assets/controllers/adminarea/orders_controller.js -> params working

**Comment by brunoprietog** [comment]
It is easier to follow conventions
