### ISSUE TITLE
How to move a stimulus controller into a gem?

### ISSUE THREAD

**Issue by kalsan** [hotwired/stimulus#573]
Hi!

Imagine an application `HelloApp` using a gem `useful_gem`. `HelloApp` contains `app/javascript/controllers/greeting.js` which turns out to be super useful for other apps using `useful_gem`. For this reasons, I'd like to move the `Greeting` stimulus controller to `useful_gem`.

How can this be achieved?

Best,
Kalsan

**Comment by marcoroth** [comment]
Hey @kalsan, while there are some ways to pack up Stimulus controller in gems I would recommend that you ship an npm package alongside your gem which contains the needed Controllers/JavaScript. This would also account for dependencies your Stimulus controller might have.

This way it's also more straight-forward to support and import the Controller from webpack(er), esbuild or importmaps in your app, without having to fine-tune the configs of your app's chosen asset management to account for the gem-scenario.

**Comment by kalsan** [comment]
Thank you @marcoroth for your advice! I'll look into that.
