### ISSUE TITLE
Strange issue with cross-controller events

### ISSUE THREAD

**Issue by elliotcm** [hotwired/stimulus#578]
I have the following markup, representing two controllers (`episode-editor` and `audio`):
```
<div
  data-controller="episode-editor"
  data-episode-editor-segments-value="<%= jsonify(@episode.segment_data) %>"
  data-episode-editor-episode-id-value="<%= @episode.id %>"
  data-action="
    audio:positionChanged->episode-editor#updatePosition
    keydown@document->episode-editor#handleKeyPress">
  <div
    data-controller="audio"
    data-action="
      episode-editor:positionChanged->audio#changePosition
      keydown@document->audio#handleKeyPress">
    <audio
      data-audio-target="audio"
      data-action="timeupdate->audio#updatePosition"
      data-episode-editor-target="audio"
      src="<%= @episode.audio.url %>">
    </audio>
    <p id="position" data-audio-target="positionText"></p>
  </div>

  <div
    data-episode-editor-target="waveform" class="waveform"
    data-action="
      click->episode-editor#changePosition:capture:stop
      mousemove->episode-editor#changePosition:capture:stop">
    <span data-episode-editor-target="waveformMarker" class="marker"></span>
    <div data-episode-editor-target="visualSegmentsContainer" class="segments"></div>
  </div>

  <table class="segments-table">
    <thead>
      <tr>
        <th>Start</th>
        <th>End</th>
        <th>Duration</th>
        <th>Type</th>
        <th>Description</th>
        <th></th>
      </tr>
    </thead>

    <tbody data-episode-editor-target="tabularSegmentsContainer"></tbody>
  </table>
</div>
```

The issue I have is that I need the audio controller to be able to trigger an update in the editor controller (to update the UI as the audio plays) *and* for the inverse to happen, the editor controller needs to trigger an update in the audio controller (to seek the audio when the user clicks in the UI).

The problem is that while the audio -> editor event works, the editor -> audio event does not.  That is to say this manually dispatched event is picked up by `audio:positionChanged->episode-editor#updatePosition`:

`audio_controller.js`
```
    this.dispatch("positionChanged", {
      detail: {
        duration: this.duration,
        newTime: this._currentTime(),
        newPercent: (this._currentTime() / this.duration) * 100,
      },
    });
```
but the inverse event is *not* picked up by `episode-editor:positionChanged->audio#changePosition`:

`episode_editor_controller.js`
```
    this.dispatch("positionChanged", {
      detail: {
        newPercent: percent,
        fastSeek: (event.buttons === 1),
      },
    });
```

Any ideas?  Is this a nesting issue? (the audio controller markup is nested within the editor markup)

**Comment by marcoroth** [comment]
Hey @elliotcm, thank your for opening this issue!

The reason why the `audio` -> `episode-editor` dispatch works, is because the controller element with the `audio` controller  is inside of the element with the `episode-editor` controller. 

Since the dispatched event bubbles up the DOM tree it's also passing the element which the `episode-editor` controller is attached on, which then triggers the action. The other way around, your `audio` controller is not going to see the event, because the dispatched event is not passing by it.

You have a few options to solve this:

**Comment by elliotcm** [comment]
Hi @marcoroth.  I'm not surprised the answer was "Elliot still doesn't know how DOM events work after 15 years in the biz".

I actually went for [option D](https://stimulus.hotwired.dev/reference/controllers#directly-invoking-other-controllers), but options A or B would be better.

Thanks for the help!
