### ISSUE TITLE
Ability to extend the Stimulus Application class

### ISSUE THREAD

**Issue by lb-** [hotwired/stimulus#586]
## Summary 

Class inheritance provides a way to achieve custom behaviour and it would be great to also allow this at the `Application` level. 

Currently, it is not easy to extend and use the `Application` class without rewriting its `static start` method. 

## Details 

In the Application code, the `start` static method references the `Application` class directly instead of using `this`. 

https://github.com/hotwired/stimulus/blob/f690a6a2e856a35ebdb78246285b734da541338e/src/core/application.ts#L19-L23

This means that even if you extend the `Application` with say a custom method override of `load`, this custom method will never get used. 

## Proposal 

Using `this` instead of `Application` should solve the issue. 

```Typescript
  static start(element?: Element, schema?: Schema): Application {
    const application = new this(element, schema)
    application.start()
    return application
  }
```

## Use case

A trivial use case to add extra behaviour to the application stop call. 

```javascript
class MyApplication extends Application {
  stop() {
    super();
    console.log('application stopped');
  }
}

const application= MyApplication.start();
application.stop();
```

**Comment by marcoroth** [comment]
Hey @lb-, thanks for opening this issue. 

I think your proposal makes sense and we could implement this. Feel free to open a pull request for it! Thank you!

**Comment by lb-** [comment]
Thanks @marcoroth - should this be documented anywhere? Or is it best left undocumented?

I would assume we would add a section around the application debugging or before the application error callback section?

https://stimulus.hotwired.dev/handbook/installing#debugging

**Comment by marcoroth** [comment]
I would probably have left it undocumented, since it's technically "just" regular class inheritance at work. But I wouldn't be opposed to having a small note/example in the documentation for it.

**Comment by lb-** [comment]
PR up https://github.com/hotwired/stimulus/pull/603
