### ISSUE TITLE
Keyboard key in event handler via action

### ISSUE THREAD

**Issue by benzen** [hotwired/stimulus#598]
I have a controller that manage a piece of html including a form.
This form contains a textarea
```
<form data-controller="MyController">
  <input data-action="keydown -> MyController#react"/>
 <textarea data-action="keydown -> MyController#react"></textarea>
</form>
```

There is two behavior that I can observe that are strange to me.
1- textarea event catched with the react action recieve an event, but tis event always have a `event.keyCode == null` and `event.which ==0`
2- input event seams never reach my action if the event contains the enter key.

Maybe the second point is due to the default behavior of browser about submit event.
But event then, is there a way to catch this event in an action, which we would be able to achieve  by registering event listener manually.

**Comment by seanpdoyle** [comment]
I've reproduced the code you've shared in a [JSFiddle](https://jsfiddle.net/rwy3s7f5/):

```html
<script type="module">
  import {Application, Controller} from "https://unpkg.com/@hotwired/stimulus@3.1.0/dist/stimulus.js"
  
  const application = Application.start()
  
  application.register("MyController", class extends Controller {
  	react(event) {
    	console.log("keyCode: ", event.keyCode)
    	console.log("which: ", event.which)
    }
  })
</script>

<form data-controller="MyController">
  <input data-action="keydown->MyController#react"/>
  <textarea data-action="keydown->MyController#react"></textarea>
</form>
```

If you remove the `" "` that surrounds the action descriptor's `->`, the correct values are reported in `MyController#react`.

Does that resolve this issue?

**Comment by marcoroth** [comment]
What @seanpdoyle said is right, the `data-action` attribute can't contain whitespaces.

re: your second point: this is because the enter-key actually submits the form. You could work around that by adding a `data-action` attribute on the `<form>` and by calling `.preventDefault()` on the event. In that case the event from the enter-key is coming through to your `react` action and logs `13` as expected:

```html
<script type="module">
  import { Application, Controller } from "https://unpkg.com/@hotwired/stimulus@3.1.0/dist/stimulus.js"
  
  const application = Application.start()
  
  application.register("MyController", class extends Controller {
    submit(event) {
      event.preventDefault()
    }
    
    react(event) {
      console.log("keyCode: ", event.keyCode)
      console.log("which: ", event.which)
    }
  })
</script>

<form data-controller="MyController" data-action="submit->MyController#submit">
  <input data-action="keydown->MyController#react"/>
  <textarea data-action="keydown->MyController#react"></textarea>
</form>
```

**Comment by benzen** [comment]
@seanpdoyle Thanks this did the trick.
Since this is an easly made error, probably that a warning should be provided to the user if the `data-action` attribute contains a white space. Because I had an event, but it was kind of empty which is strange.

And the team has done a great job of warning in the console.
