### ISSUE TITLE
Event names containing the letter `.` are understood to be filters

### ISSUE THREAD

**Issue by NakajimaTakuya** [hotwired/stimulus#612]
from: https://github.com/hotwired/stimulus/pull/442#issuecomment-1330223619

Event names containing a dot, like jQuery's event namespace, are recognized as filter syntax.

For example.
https://getbootstrap.com/docs/4.2/components/modal/
https://api.jquery.com/event.namespace/

**Comment by songjiz** [comment]
@NakajimaTakuya Thanks for opening this issue.

**Comment by radiantshaw** [comment]
I feel like this issue won't just be limited to dots, as any number of libraries could use any convention to name their events, so the solution to this should be generalised.

**Comment by NakajimaTakuya** [comment]
@radiantshaw 
Yes, there are other letters that can be misinterpreted when used.
The letter C is used in the jQuery namespace, so it may have a single biggest impact.　So it might be a good idea to focus only on this issue and introduce escaping, as you suggest.
