### ISSUE TITLE
The new keyboard modifier for actions breaks Bootstrap actions

### ISSUE THREAD

**Issue by ecmel** [hotwired/stimulus#614]
The following action does not get called with version 3.2.0

```
 data-action="show.bs.modal->controller#show"
```

Most probably the cause is the following pull request:

https://github.com/hotwired/stimulus/pull/442

**Comment by NakajimaTakuya** [comment]
@ecmel 
Thanks for the report.
This has already been incorporated into the main branch.

https://github.com/hotwired/stimulus/issues/612
https://github.com/hotwired/stimulus/pull/613

**Comment by NakajimaTakuya** [comment]
@ecmel 
It seems that v3.2.1 has been released.
And it includes a fix for this, so please try v3.2.1.

**Comment by ecmel** [comment]
Thank you, fixed in 3.2.1
