### ISSUE TITLE
Value change callbacks are trigged by simply defining the value

### ISSUE THREAD

**Issue by fabian-as** [hotwired/stimulus#622]
If I define a value without a default like
```javascript
static values = { "name": String }
```
the corresponding change callback `nameValueChanged()` will be triggered, even if the value is never set or changed.
I cobbled together a minimal working example
```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <script type="module">
      import { Application, Controller } from "https://unpkg.com/@hotwired/stimulus/dist/stimulus.js"
      window.Stimulus = Application.start()

      Stimulus.register("hello", class extends Controller {
        static values = { "name": String }

        nameValueChanged(oldName, newName) {
          console.log("Name was changed from", oldName, " to ", newName);
        }
      })
    </script>
  </head>
  <body>
    <div data-controller="hello"></div>
  </body>
</html>
```
which will print `Name was changed from <empty string>  to  undefined`.
Any chance on getting this fixed? Or is this the expected behavior?
I'm not quite sure, but I guess the reason is

https://github.com/hotwired/stimulus/blob/f690a6a2e856a35ebdb78246285b734da541338e/src/core/value_observer.ts#L76

where `defaultValue` should be checked against `null` too.

**Comment by adrienpoly** [comment]
yes this is by design 

https://stimulus.hotwired.dev/reference/values#change-callbacks

> Stimulus invokes each change callback after the controller is initialized and again any time its associated data attribute changes. This includes changes as a result of assignment to the value’s setter.

**Comment by marcoroth** [comment]
Yeah, this is by design so that you can react/initialize the initial state.

```js
static values = { "name": String }
```

is the shortcut for:
```js
static values = {
  "name": {
    type: String,
    default: ""
  }
}
```

And on connect it's going from `undefined` to `""` since that's the default value.

Similarly, if you define:
```html
<div data-controller="hello" data-hello-name-value="John"></div>
```

It would invoke the change callback once on connect with the new value being `"John"`

I hope this helps!
