### ISSUE TITLE
key event example not working

### ISSUE THREAD

**Issue by olimart** [hotwired/stimulus#630]
The example from [KeyboardEvent Filter](https://stimulus.hotwired.dev/reference/actions#keyboardevent-filter) does not seem to be working running `3.2.1` version.
Nothing happens when pressing the `k` key, but it works fine with click event.

```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <script type="module">
    import { Application, Controller } from "https://unpkg.com/@hotwired/stimulus/dist/stimulus.js"
    window.Stimulus = Application.start()

    Stimulus.register("hello", class extends Controller {
      print() {
        console.log("hello")
      }
    })
  </script>
</head>
<body>
  <div data-controller="hello">
    <span data-action="keydown.k->hello#print">triggered by key event: k key</span>
  </div>
</body>
</html>
```

[JS Fiddle version](https://jsfiddle.net/#&togetherjs=fpuAT2BtdQ)

**Comment by tsmd** [comment]
You probably need `tabindex` attribute to receive focus.
https://codepen.io/tsmd/pen/WNKreVq?editors=1011

**Comment by olimart** [comment]
Thanks @tsmd didn't realize `tabindex` matters 👍

**Comment by zb010** [comment]
I stumbled upon this as well. 
For me `keydown` works fine, but adding a keystroke like `keydown.k` does not.
I tried adding setting `tabindex="0"` but it doesn't work.
For me the [linked codepen](https://codepen.io/tsmd/pen/WNKreVq?editors=1011) above isn't working as well. 
Running on `"@hotwired/stimulus": "^3.2.1"`

**Comment by olimart** [comment]
@zb010 it seems to work once the element is "active"
(notice how the text is selected in the HTML pane)

![Capture d’écran, le 2023-02-28 à 08 31 29](https://user-images.githubusercontent.com/547754/221868757-8be8f6cb-258c-4e90-9918-c0f16e09d32d.png)
