### ISSUE TITLE
Bug in target callbacks?

### ISSUE THREAD

**Issue by JohnAnon9771** [hotwired/stimulus#631]
Could someone explain to me why when using this way of defining target...

```html
<input data-target="character-counter.input"
```

`inputTargetConnected` does not fire?

**Comment by marcoroth** [comment]
Hey @JohnAnon9771, the `data-target` attribute is deprecated and will be removed in a future version of Stimulus. You should rewrite your target to `data-character-counter-target="input"`.

But either way, it should work as expected if you have a controller at `app/javascript/controllolers/character_counter_controller.js` with something like:

```js
import { Controller } from "@hotwired/stimulus"

export default class extends Controller {
  static targets = ["input"]

  inputTargetConnected() {
    console.log("input target connected")
  }
}
```

**Comment by JohnAnon9771** [comment]
> Hey @JohnAnon9771, the `data-target` attribute is deprecated and will be removed in a future version of Stimulus. You should rewrite your target to `data-character-counter-target="input"`.
> 
> But either way, it should work as expected if you have a controller at `app/javascript/controllers/character_counter_controller.js` with something like:
> 
> ```js
> import { Controller } from "@hotwired/stimulus"
> 
> export default class extends Controller {
>   static targets = ["input"]
> 
>   inputTargetConnected() {
>     console.log("input target connected")
>   }
> }
> ```
> 
> Also, your `<input>` needs to have the `data-controller` attribute on itself or an a parent element:
> 
> ```
> <div data-controller="character-counter">
>   <input data-character-counter-target="input">
> </div>
> 
> 
> 
> <input data-controller="character-counter" data-character-counter-target="input">
> ```

Okay, thank you very much for the clarifying answer.
