### ISSUE TITLE
multiple actions on `turbo:submit-end` leads to inconsitent behavior

### ISSUE THREAD

**Issue by luizkowalski** [hotwired/stimulus#635]
I have a form like this

```
<%= form_tag messages_path, data: { action: 'turbo:submit-start->loader#toggleLoader turbo:submit-end->loader#toggleLoader messages#handleCreation' } do %>
  ....
```

what I'm trying to do is upon form submission, a loader will appear on the page, indicating that the request is being processed. when the request finishes, I want to trigger two actions: one to toggle the loader so it disappears and another to show a banner if the process fails. 

the problem I'm seeing is that the rightmost action at `turbo:submit-end` will get processed instantly, just after I submit the form, it doesn't wait for the actual for submission to end. here are the scenarios:

 1) when `messages#handleCreation` is the rightmost
* gets called right away, doesn't wait for the request to finish
*  I get a `SubmitEvent` event type instead of a `FormSubmission` object 
* obviously `event.detail.formSubmission` fails since `SubmitEvent` has no `detail` object
* the loader works as intended, getting toggled at the end of the request

2) when `loader#toggleLoader` is the rightmost
* also gets called right away, doesn't wait for the request to finish
* the loader just blinks, getting toggled instantly, instead at the end of the request
* `messages#handleCreation` works fine, I do get a `FormSubmission` object and at the end of the request 

looks like `turbo:submit-end` event does not support multiple actions.

**Comment by dmcge** [comment]
I think you have to repeat the event name: `turbo:submit-start->loader#toggleLoader turbo:submit-end->loader#toggleLoader turbo:submit-end->messages#handleCreation`

**Comment by luizkowalski** [comment]
hmm, weird, there are no mentions about this [in the docs](https://stimulus.hotwired.dev/reference/actions#multiple-actions)

**Comment by marcoroth** [comment]
It's not specifically mentioned in the "Multiple Actions" section of the docs, but it's mentioned here: https://stimulus.hotwired.dev/reference/actions#event-shorthand

If you don't specify an event for an action it will use the event shorthand if the given element type has one.

@luizkowalski were you able to solve your issue with the suggestion @dmcge provided?

**Comment by luizkowalski** [comment]
hey marco! thanks for the link, yes, the solution proposed by @dmcge worked but I ended up doing something different. I created a "loader component" that I can just drop in any page I want like this:

```erb
<%= content_tag(:div, data: { controller: "loader" }, class: "#{extra_classes}") do %>
  <%= content_tag(:div, id: 'spinner', role: "status", class: "hidden", "data-loader-target": 'loader') do %>
     ...
  <% end %>
<% end %>
```

and I hooked up the controller like this

```javascript
export default class extends Controller {
  static targets = [ "loader" ]

  connect() {
    document.addEventListener('turbo:submit-start', this.toggle.bind(this))
    document.addEventListener('turbo:submit-end', this.toggle.bind(this))
  }

  toggle() {
    toggle(this.loaderTarget)
  }
}
```

so now I can just render the loading animation wherever I want without having to hook extra events in the forms. unrelated but I wanted to give more context

closing this one now, thanks for the clarification
