### ISSUE TITLE
Call another controller method from controller

### ISSUE THREAD

**Issue by helmiattastify** [hotwired/stimulus#637]
Hello, I'm new to stimulus

So, the case is I want to access another method controller from the controller

_controllers/toast_controller.js_
```
import { Controller } from "@hotwired/stimulus"
import Swal  from "sweetalert2"
export default class extends Controller {
    show(){
    }
   confirm(){
    }
}
```

_controllers/main_controller.js_
```
import { Controller } from "@hotwired/stimulus"
import Toast from "./toast_controller"
export default class extends Controller {
    connect(){
       Toast.show();
    }
   confirm(){
    }
}
```

Still failed, 

I haven't met a good tutorial yet. any one can help?

**Comment by lb-** [comment]
Stackoverflow or the Stimulus discussion forum may be better for this kind of question. 

https://stackoverflow.com/questions/tagged/stimulusjs
https://discuss.hotwired.dev/

You may also need to have more details in your question.

**Comment by marcoroth** [comment]
Hey @helmiattastify, adding to what @lb- said, you can also join the Hotwire Discord for more interactive help.

There are a few routes that you can do to solve your problem.

* Outlets: https://stimulus.hotwired.dev/reference/outlets
* Dispatch an event on the controller element: https://stimulus.hotwired.dev/reference/controllers#cross-controller-coordination-with-events
* Directly invoke the other controller action: https://stimulus.hotwired.dev/reference/controllers#directly-invoking-other-controllers 

I hope this helps! 🙌🏼
