### ISSUE TITLE
Clarify identifiers implementation

### ISSUE THREAD

**Issue by amkisko** [hotwired/stimulus#639]
Hey!

In general the question is: could you please clarify current implementation of controllers identifiers? What are the decisions behind it?
Reference: https://stimulus.hotwired.dev/reference/controllers#identifiers

Main issues that I found:
- it does not follow Rails routes patterns
- possibility of collision will persist any ways (`users/index_controller.js` vs `users__index_controller.js` - is this intended?)

The logic I use that does not follow official guidelines and quite hard to share with others:
- `filepath.replace(/[^\p{L}\p{N}]+/gu, "-")`
- put controller under `views` folder in the same place near the view template (e.g. `views/users/orders/edit.html.erb` might have `views/users/orders/edit_controller.ts` and `views/users/orders/_form.html.erb` might have `views/users/orders/_form_controller.ts` etc)
- controller identifier will be e.g. `users-orders-index`

**Comment by lb-** [comment]
Not a maintainer but I think that this issue makes more sense on the package https://github.com/hotwired/stimulus-webpack-helpers

Additionally, I think that the docs referencing the way the require context will map file names to controller identifiers could cause confusion if you are not using that webpack helper package.

This does not really answer the original question though.

**Comment by amkisko** [comment]
This story is mainly about convention over controller identifiers, sure you can put controller definitions anywhere.

We can try debating regarding JavaScript and what's the reason to not assume it as a part of view, same goes to css, remember that you have to bring things at least in layout view with some helpers or manually, and eventually it will become a part of view, although most probably hidden.

The main reason asking the question here is to clarify current convention on controller identifiers and probably try to get rid of multiple dashes at least. :)

**Comment by amkisko** [comment]
Closing this since it's not a blocker anymore for me personally, resolved it by doing this: https://gist.github.com/amkisko/6f11f0812be8fc8bad6a14654875718e
