### ISSUE TITLE
Question: Could Stimulus be used without using Rails in JS/TS-only projects?

### ISSUE THREAD

**Issue by aderchox** [hotwired/stimulus#640]
Hi, I just wonder if Stimulus is a tool that's supposed to be used with other Rails Hotwire tools such as Turbo, or it can be used alone in JS/TS-only projects as well?
I couldn't find any tutorials on the latter case, so I suppose it's a Rails tool only?

**Comment by dhh** [comment]
Hotwire has no dependencies on Rails. You can use it with whatever backend you like.

**Comment by SimonHeimberg** [comment]
For how to do it, see on https://stimulus.hotwired.dev/handbook/installing#using-other-build-systems
I found this doc after searching for a long time :see_no_evil:. The link just in case somebody else has the same problem.
