### ISSUE TITLE
Allow dispatch target type to not be the same as the controller element type

### ISSUE THREAD

**Issue by lb-** [hotwired/stimulus#642]
### Summary

When using generics to declare a more specific element type on the controller, the `dispatch` target type is linked to that same type and it is no longer possible (without overrides or type checking warnings) to dispatch against a target of any kind of element.

Not sure if this is a bug but it is probably an unintended side effect of allowing a type signature for controllers via generics completed in https://github.com/hotwired/stimulus/pull/529

### Steps to reproduce

1. Create a new controller (TypeScript) similar to this, where the Controller's type is `HTMLInputElement` (e.g. not a generic `Element` or `HTMLElement`.
```
import { Controller } from '@hotwired/stimulus';

export class ExampleController extends Controller<HTMLInputElement> {
  connect() {
    const main = document.querySelector('main') as HTMLElement;

    this.dispatch('Connected!', { target: main });
  }
}
```
2. Expected: I should be able to use the documented `dispatch` callback with any target element - as per https://stimulus.hotwired.dev/reference/controllers#cross-controller-coordination-with-events (see `dispatch accepts additional options as the second parameter as follows:`)

3. Actual: I get a type error advising that the dispatch target element `HTMLElement` does not match the `HTMLInputElement` type.

```
Type 'HTMLElement' is missing the following properties from type 'HTMLInputElement': accept, align, alt, autocomplete, and 53 more.ts(2740)
```

A similar issue also happens if we were to pass in something like `document` to the target.

### Screenshots

<img width="902" alt="Screenshot 2023-01-24 at 11 08 17 am" src="https://user-images.githubusercontent.com/1396140/214192837-fbf04838-f2ae-4917-ab53-c4ce8f000da3.png">
<img width="804" alt="Screenshot 2023-01-24 at 11 10 16 am" src="https://user-images.githubusercontent.com/1396140/214192844-0c519143-7d6e-4c1e-b57f-3b6280047643.png">

### Potential solution 

Allow the `target` type to be something like:
```TypeScript
target?: ElementType | Element;
```

https://github.com/hotwired/stimulus/blob/eedb8ed2ff50fa5ad5319bc0e456d684046b2dbd/src/core/controller.ts#L82

```
 dispatch(
    eventName: string,
    { target = this.element, detail = {}, prefix = this.identifier, bubbles = true, cancelable = true } = {}
  ) {
    const type = prefix ? `${prefix}:${eventName}` : eventName
    const event = new CustomEvent(type, { detail, bubbles, cancelable })
    target.dispatchEvent(event)
    return event
  }
```

**Comment by marcoroth** [comment]
This seems to work as expected now:

![Screenshot 2023-01-24 at 15 07 56](https://user-images.githubusercontent.com/6411752/214316129-5abb11d1-cfff-46bd-a8c1-d78629fbb7af.png)

**Comment by lb-** [comment]
Awesome. Thank you
