### ISSUE TITLE
Issue with using `this` inside `afterLoad` static method

### ISSUE THREAD

**Issue by lb-** [hotwired/stimulus#652]
### Problem

The afterLoad method is confusingly not called with a `this` context of the controller constructor but is instead undefined.

TypeScript is advising that `this` will be the controller constructor but at runtime it is failing.

### Steps to reproduce

Create a controller

```ts
export class LoaderController extends Controller {
  static values = {
    durationSeconds: { type: Number, default: 30 },
  };

  static afterLoad(identifier: string, application: Application) {
    const { controllerAttribute } = application.schema;
    console.log('afterLoad test', this); // this is undefined
    console.log('afterLoad stuff', {identifier, controllerAttribute });
    console.assert(this.values.durationSeconds.default, 30); // errors as this is undefined
  }
}
```

Expect that the `this` will be the controller constructor. Instead it is undefined.

### Potential solution

https://github.com/hotwired/stimulus/blob/8217e9b1224c5f8a82e9655574ed0d92173af74e/src/core/router.ts#L58

```ts
 const afterLoad = (definition.controllerConstructor as any).afterLoad?.bind(controllerConstructor)
```

**Comment by ippeiukai** [comment]
bitten by this bug. hope to have a patch release.

**Comment by marcoroth** [comment]
@ippeiukai this fix is shipping in the next release.

If you don't want to wait you can use the latest dev-build from `main` using:
```
yarn add @hotwired/stimulus@https://github.com/hotwired/dev-builds/archive/refs/tags/@hotwired/stimulus/eda0f9d.tar.gz
```
