### ISSUE TITLE
Request to update Yarn version or move to npm

### ISSUE THREAD

**Issue by lb-** [hotwired/stimulus#657]
Yarn version is still at v1 which causes issues when setting up a new version of Yarn on a new device.

It would be great if this project did not rely on Yarn as there is less risk of major backwards compatibility issues if just using the npm approach.

Alternatively, updating to Yarn v2 would be good.

Happy to help with this if needed.

**Comment by marcoroth** [comment]
I'm not sure if it's currently worth to migrate away from Yarn v1. It's certainly not desirable to migrate "back" to npm imho. 

If we migrate away from Yarn v1 I feel like the only considerable option right now is pnpm. Yarn v1 still seems the "most popular", at least at the time being. 

Can you elaborate what issues you were facing with yarn when setting up a new device? It's a first that I hear that to be honest.
