### ISSUE TITLE
about input CompositionEvent

### ISSUE THREAD

**Issue by langziyang** [hotwired/stimulus#670]
hi, i am chinese, i want add CompositionEvent action for input.

when i use input action and input chinese use pinyin, i got same log
so, how can i get start and end event?
![企业微信截图_16808568096294](https://user-images.githubusercontent.com/2345387/230575147-64aae8c6-c589-4934-87ca-f5a38932a669.png)

**Comment by ZhenhangTung** [comment]
Hey @langziyang , I'll try to summarize the problem you're facing.
**The problem**: You want to add a CompositionEvent listener to the input, right?
**The challenge**: You bind an input event listener, so the event type is `input`. You want to know how to add `compositionstart` and `compositionend` event listener to this input. 

[According to the docs](https://stimulus.hotwired.dev/reference/actions#multiple-actions), you could add these listener to the input:
```
<div data-controller="composition">
    <input id="input" data-action="compositionstart->composition#handleChinese compositionend->composition#handleChinese">
</div>
```

```
# composition_controller.js

import { Controller } from "@hotwired/stimulus"

export default class extends Controller {
    handleChinese(event) {
        console.log(event)
    }
}
```
Here is the console logs:
<img width="722" alt="截屏2023-05-18 上午11 34 58" src="https://github.com/hotwired/stimulus/assets/8170159/951520ff-b068-4085-b56e-91d9232c0e39">

Hope it solves your problem 😄
