### ISSUE TITLE
No Upgrade Guide, No Versioning Information, Broken Links, Just One Docs Website

### ISSUE THREAD

**Issue by SampsonCrowley** [hotwired/stimulus#674]
It is not easy to find version specific information on stimulus.

NOW, I'm fully aware, no one wants to keep supporting older outdated versions of a project.

But when this is a library that has been around since the early days of rails, there are lots of legacy users that might need to know what syntaxes are and arent supported by a specific version.

When the readme just says "go to the website" without any references to the commit-local documentation, there's not a lot of information available on what the version a specific individual can work with.

There's not an upgrade guide on the website pointing to changes in API, and no ability to select the docs for an older version, which would lead someone unfamiliar with the library who was just onboarded to a legacy codebase to believe it has never changed; which is incorrect.

when I brought up that even just the documentation in the code itself is currently incorrect, it was met with ["just go to the website"](#671) which doesn't work when the website doesn't match that version anymore

What are some of the things we can reasonable do to work with the real world and not make people think all versions are the same?

**Comment by marcoroth** [comment]
Thanks for bringing this up, @SampsonCrowley!

While you are totally right that most of the stuff you listed isn't available on the website, the reality is that there hasn't been any breaking changes in the history of library, which would have justified the complexity of hosting multiple version of the docs. Everything from Stimulus 1.0.0 still works on the latest version.

There are two things, which come to mind for an Upgrade guide:
- The "new" target Syntax from `data-target="[identifier].[target]"` to `data-[identifier]-target="[target]"`
- and the "new" npm package name from `stimulus` to `@hotwired/stimulus`

But in both cases the old variant still works. But I agree, that it would make sense if we started to list that on the website somewhere.

The only reason I could think of regarding adding version information to the docs site right now would be to note from which version a certain API is available. For example the "Outlets API" could have a badge which says "From version 3.2.1".

**Comment by SampsonCrowley** [comment]
"there haven't been any breaking changes"

That's not true when you're coming from a new documentation standpoint.

Version 2 is *backwards compatible* but reading V2 and V3 docs while using
V1 will lead to confusion. V2 *absolutely* has new features. For example
the object syntax for defining values with defaults. Attempting to use this
in V1 will crash your controller

**Comment by adrienpoly** [comment]
Is there something preventing you from upgrading to V3 ? As Marco mentioned there haven't been any real breaking changes. Upgrading should be straightforward by replacing the  npm package name from `stimulus` to `@hotwired/stimulus`

**Comment by marcoroth** [comment]
Yeah, there shouldn't really be anything holding one back to upgrade to the latest version. You can even keep the "old" `stimulus` if you wanted to.

**Comment by danini-the-panini** [comment]
I am dissatisfied with the result of this issue. The new target syntax change IS a breaking change, and on very large code bases makes it prohibitively difficult to upgrade to v3.

**Comment by danini-the-panini** [comment]
Oh my bad. It just said "a future version of stimulus" and since it was showing up in 2 I thought it would be gone by 3 🤦🏻‍♀️
