### ISSUE TITLE
Using ajax request turbo-stream in stimulus doesn't work

### ISSUE THREAD

**Issue by witcan** [hotwired/stimulus#689]
<img width="1687" alt="image" src="https://github.com/hotwired/stimulus/assets/48895485/69b3b7b0-0692-4828-88b0-0bf975130990">

<img width="854" alt="image" src="https://github.com/hotwired/stimulus/assets/48895485/443218fd-198b-4a2f-b5e6-d64e54d8216a">

<img width="878" alt="image" src="https://github.com/hotwired/stimulus/assets/48895485/d90197ec-de36-4019-8d17-771676629b94">

<img width="1452" alt="image" src="https://github.com/hotwired/stimulus/assets/48895485/df2265e8-6924-4f11-a1e8-fc9df3e50d30">

**Comment by witcan** [comment]
The update request has been triggered on the page, and the returned content is as follows, but the dom on the html has not been updated.

**Comment by marcoroth** [comment]
Hey @witcan, you can simplify your Stimulus controller a lot if you make use of the `@rails/request.js` package and use Stimulus Values for passing over the `crowd_id` and `crowd_status_id`:
```js
import { Controller } from "@hotwired/stimulus"
import { patch } from "@rails/request.js"

export default class extends Controller {
  static values = {
    id: Number,
    statusId: Number
  }

  update_status() {
    patch(`/operation/crowds/${this.idValue}`, {
      body: {
        crowd: {
          crowd_status_id: this.statusIdValue
        }
      }
    })
  }
}
```

Make sure to also update your `<a>` tag accordingly:
```html
<a class="dropdown-item" data-controller="crowd" data-action="click->crowd#update_status" data-crowd-status-id-value="<%= ... %> data-crowd-id-value="<%= ... %> .../>...</a>

**Comment by witcan** [comment]
@marcoroth Changing to `@rails/request.js` can work very well, why can't use jQuery ajax?

**Comment by marcoroth** [comment]
Technically it should also work with the jQuery `$.ajax(...)` function, you just need to make sure that you are submitting the right headers and MIME-Type. The benefit of using `@rails/request.js` is that it's configured properly out of the box, so that's why I'd recommend to use it.

**Comment by witcan** [comment]
> 
Thanks a lot, I tried both ways below and it works fine now!
```js
patch(`/operation/crowds/${crowd_id}`, {
  headers: {
    "Accept": "text/vnd.turbo-stream.html, text/html, application/xhtml+xml",
  },
  body: {
    crowd: {
      crowd_status_id: crowd_status_id
    }
  }
})
```
and
```js
$.ajax({
  url: "/operation/crowds/" + crowd_id,
  type: "PATCH",
  headers: {
    "Accept": "text/vnd.turbo-stream.html, text/html, application/xhtml+xml"
  },
  data: {
    crowd: {
      crowd_status_id: crowd_status_id
    }
  },
  success: function (res) {
    Turbo.renderStreamMessage(res)
  }
});
```

**Comment by witcan** [comment]
> Technically it should also work with the jQuery `$.ajax(...)` function, you just need to make sure that you are submitting the right headers and MIME-Type. The benefit of using `@rails/request.js` is that it's configured properly out of the box, so that's why I'd recommend to use it.
> 
> Edit: You'll also need to make sure to pass the response body you get from your `$.ajax(...)` call into `Turbo.renderStreamMessage(responseBody)` for Turbo to be able to process the Turbo Streams you return from the server-side.

@marcoroth Thanks a lot, I tried both ways below and it works fine now!
```js
patch(`/operation/crowds/${crowd_id}`, {
  headers: {
    "Accept": "text/vnd.turbo-stream.html, text/html, application/xhtml+xml",
  },
  body: {
    crowd: {
      crowd_status_id: crowd_status_id
    }
  }
})
```
and
```js
$.ajax({
  url: `/operation/crowds/${crowd_id}`,
  type: "PATCH",
  headers: {
    "Accept": "text/vnd.turbo-stream.html, text/html, application/xhtml+xml"
  },
  data: {
    crowd: {
      crowd_status_id: crowd_status_id
    }
  },
  success: function (res) {
    Turbo.renderStreamMessage(res)
  }
});
```

**Comment by marcoroth** [comment]
Awesome, glad you figured it out @witcan! 🙌🏼

**Comment by maxence33** [comment]
Thanks a lot for the question and the explanation. 
Though I had a case : 
```
fetch("/order_updater",
   {
    method: "POST",
    body: JSON.stringify({content: array}),
    headers: {
      "Accept": "text/vnd.turbo-stream.html, text/html, application/xhtml+xml",
      'X-CSRF-Token': csrf,
       },  
    credentials: "same-origin",
    }).then(response => {
      Turbo.renderStreamMessage(response.body)
    })
```
This triggered a console error : `Node.appendChild: Argument 1 is not an object.`

Though the below worked
```
fetch("/order_updater",
   {
      method: "POST",
      body: JSON.stringify({content: array}),
      headers: {
        "Accept": "text/vnd.turbo-stream.html, text/html, application/xhtml+xml",
        'X-CSRF-Token': csrf,
      },  
      credentials: "same-origin",
    }).then (response => response.text())
    .then(html => Turbo.renderStreamMessage(html));
```
as per here https://fly.io/ruby-dispatch/turbostream-fetch/

**Comment by jimmynyasulu98** [comment]
> > Technically it should also work with the jQuery `$.ajax(...)` function, you just need to make sure that you are submitting the right headers and MIME-Type. The benefit of using `@rails/request.js` is that it's configured properly out of the box, so that's why I'd recommend to use it.
> > Edit: You'll also need to make sure to pass the response body you get from your `$.ajax(...)` call into `Turbo.renderStreamMessage(responseBody)` for Turbo to be able to process the Turbo Streams you return from the server-side.
> 
> @marcoroth Thanks a lot, I tried both ways below and it works fine now!
> 
> ```js
> patch(`/operation/crowds/${crowd_id}`, {
>   headers: {
>     "Accept": "text/vnd.turbo-stream.html, text/html, application/xhtml+xml",
>   },
>   body: {
>     crowd: {
>       crowd_status_id: crowd_status_id
>     }
>   }
> })
> ```
> 
> and
> 
> ```js
> $.ajax({
>   url: `/operation/crowds/${crowd_id}`,
>   type: "PATCH",
>   headers: {
>     "Accept": "text/vnd.turbo-stream.html, text/html, application/xhtml+xml"
>   },
>   data: {
>     crowd: {
>       crowd_status_id: crowd_status_id
>     }
>   },
>   success: function (res) {
>     Turbo.renderStreamMessage(res)
>   }
> });
> ```

Had the same problem  for about 2 days and this has really helped me
