### ISSUE TITLE
How to know when every stimulus controllers are connected ?

### ISSUE THREAD

**Issue by lecrapal** [hotwired/stimulus#698]
Hello,

I can't find any documentation or API reference on how to retrieve global states on the application.

I am using Stimulus with Symfony and my goal is to display a loading screen while all my Stimulus controllers finish their "connect()" action, knowing that many make AJAX calls.

Has anyone ever encountered this problem?
How to solve it?

Thank you

**Comment by lb-** [comment]
That's a tricky problem to solve, connect only gets called once a controller connects to the DOM. If you have five registered controllers and only four have DOM elements on the initial page load... what do you expect to happen?

It's also usually not a good idea to block the entire UI with a loading screen. The point of using something like Stimulus is to avoid the downsides of a JS single page application where nothing can show on screen until the JS has been parsed. 

Nonetheless, here is an approach. 

1. Give any controllers you want to have this loading behaviour a value e.g. `data-my-table-ready-value="false"`.
2. Then when your controller loads, change this value on connection. `this.loadingValue = true;`. 
3. Add some global CSS to hide/blur or do whatever you need based on any values that match the pattern.

You could do this generically with a consistent data attribute and/or class. You could even add a controller that removes itself when it receives a specific event.

The idea is you go for a CSS approach to change the visual state, driven by data attributes that get removed once the controller is ready.


Another approach, loading targets. For the controllers that need to show a loading state, use a target. Once your Promise has resolved, remove all loading elements. Be sure to remove them even if you get an error. 

```html
<div data-controller="my-table">
  <span data-my-table-target="loader">Loading...</span>
</div>
```

```js
export class extends Controller {
  static targets = ['loader'];
  connect() {
    loadStuff.finaly(() => {
      this.loaderTargets.forEach(element => { element.remove(); } );
    });
  }
}
```
