### ISSUE TITLE
https://stimulus.hotwired.dev deployment to prod

### ISSUE THREAD

**Issue by tellodaniel** [hotwired/stimulus#721]
When https://stimulus.hotwired.dev will be deployed? Seems that we made changes to the docs that are not being reflected in production. Thanks

**Comment by marcoroth** [comment]
Hey @tellodaniel, I guess you are referring to the changes from #705?

They have been part of the last deploy 2 weeks ago, here: https://github.com/hotwired/stimulus-site/commit/9f54ee6afa7f56f883a413f1101f038e151e9087#diff-fa61749052df405bea9820a727b69a1c29092412f21f58f99441c631a0ac39cd

And it also seems like they are deployed:

<img width="946" alt="CleanShot 2023-09-19 at 10 37 49@2x" src="https://github.com/hotwired/stimulus/assets/6411752/57075619-8404-40d9-92f8-51a9d66075a8">


Or are you referring to something else?

**Comment by tellodaniel** [comment]
Right @marcoroth thanks! 
I visited before and had the issue as a draft.
