### ISSUE TITLE
Is 3.2.2 unpkg version correct?

### ISSUE THREAD

**Issue by wyaeld** [hotwired/stimulus#734]
Version at 3.2.2 distribution url has 3.2.1 header comments.  Different size to the prior one on their dist though, just incorrect comments?

![image](https://github.com/hotwired/stimulus/assets/157392/990bf5b2-5922-47a9-8813-5b45ac20f8dc)

**Comment by marcoroth** [comment]
Hey @wyaeld, yes, it's just a misleading comment.

We had a similar discussion in https://github.com/hotwired/stimulus/issues/714

**Comment by wyaeld** [comment]
thanks, I just manually updated the comment on my side since we download and serve directly.  I'll close.
