### ISSUE TITLE
Stimulus.js on Unpkg.com is 404

### ISSUE THREAD

**Issue by jspooner** [hotwired/stimulus#737]
I'm using Stimulus [without a build system](https://stimulus.hotwired.dev/handbook/installing#using-without-a-build-system), and the JS file just became unavailable.  

```
date
Mon Oct 30 13:21:31 PDT 2023
curl  https://unpkg.com/@hotwired/stimulus/dist/stimulus.js
Cannot find package @hotwired/stimulus@latest%  
```

**Comment by jspooner** [comment]
And it's back up now.

```
curl  https://unpkg.com/@hotwired/stimulus/dist/stimulus.js
Found. Redirecting to /@hotwired/stimulus@3.2.2/dist/stimulus.js%                                                                                      
date                                                       
Mon Oct 30 13:27:06 PDT 2023
```

Can this URL be used for production apps?

**Comment by marcoroth** [comment]
If you are using `stimulus-rails`: it includes a copy of the dist file, so you don't need to bundle/install it.

Alternatively, you can also download and vendor the dist file and serve it from your own server.

But I think it should be safe to use for production apps, these services strive for high uptime. But also, those CSN services can obviously have downtimes from time to time which are beyond our control.

There are also alternatives like JSDeliver or esm.sh if you are looking for another service.
