### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by sh-jthorpe** [hotwired/stimulus#740]
I logged an issue (and provided a tentative fix) 3 weeks ago - haven't heard anything since.

I understand there may be many totally valid reasons for that.

The purpose of this issue is to suggest that if the project isn't being actively maintained anymore, that should be noted in the project readme.

**Comment by marcoroth** [comment]
Hey @sh-jthorpe, sorry for the delay. This repo isn't dead. There's just been a lot of other stuff happening in the Hotwire world between all the conferences. Stimulus is on top of my list after RubyConf. Thanks for understanding! 🙏🏼
