### ISSUE TITLE
classList.remove() doesn't do anything on target

### ISSUE THREAD

**Issue by entoncode** [hotwired/stimulus#780]
I currently have an issue that I don't know if it is really related to Stimulus or not. It's just the only difference I have in this.

I have following really simple controller `dialog_controller.js`:
```js
import { Controller } from 'stimulus';

export default class extends Controller {
    static targets = ['dialog'];

    connect() {
        this.dialogTarget.classList.add('dialog');
    }

    open() {
        this.dialogTarget.classList.add('opened');
    }

    close() {
        this.dialogTarget.classList.remove('opened');
    }
}
```

And following html markup:

```html
<div data-controller="dialog" data-action="click->dialog#open">
    <h3>[...]</h3>
    <p>[...]</p>
    <div class="dialog" data-dialog-target="dialog">
        <div class="dialog-backdrop" data-action="click->dialog#close"></div>
        <div class="dialog-content" aria-modal="true">
            <div class="dialog-header">[...]</div>
            <div class="dialog-body">[...]</div>
        </div>
    </div>
</div>
```

As implied by the controller structure, the dialog div is only visible when featuring both classes `dialog` and `opened`.

When I click on the outer div, whichs action runs `dialog#open`, the `opened` class is added as expected.
However, whenever the `dialog#close` method runs, the class isn't removed.

I have debugged and logged everything there is in the controller, in the html and in the Developer Console, the method is run for sure, the dialogTarget is correct and the class is present in the DOMTokenList as given.
Still, the `classList.remove()` does not work, it doesn't print any error and it returns `undefined` (as expected).

I would be less surprised if the add() didn't work as well, but that one does, so I am lost.
Since this works in native JavaScript as well as through the Developer Console, Stimulus is the only thing I see as a possible source.
Any ideas to why this is?

**Comment by entoncode** [comment]
Additionally, attempting to reset the classes via `this.dialogTarget.className = 'dialog';` doesn't work as well!

**Comment by entoncode** [comment]
Okay, so when I debug a little bit more using:
```js
close() {
        console.log(
            this.dialogTarget.classList.contains('opened'),
            this.dialogTarget.classList.length,
            this.dialogTarget.classList
        );
        this.dialogTarget.classList.remove('opened');
        console.log(
            this.dialogTarget.classList.contains('opened'),
            this.dialogTarget.classList.length,
            this.dialogTarget.classList
        );
    }
```
In the console it prints:
![grafik](https://github.com/user-attachments/assets/cd80f0f3-c00e-4a43-ba1d-ed886eb13722)
However, when I open the DOMTokenList in the console to view the live version, it looks like:
![grafik](https://github.com/user-attachments/assets/55018ab6-82f0-431d-9e07-96b90bdd8b91)
So it seems to immediately reverse it changes or so for some reason. 

I didn't really look to much into it from the Stimulus side of things so perhaps anyone knows a possible explanation? Is this maybe wanted behaviour?

**Comment by entoncode** [comment]
Ah okay, I mean I should've seen that from the start... Embarassing mistake.

For future reference, the close button with the close action is within the div which has `dlick->dialog#open`, so first it closes but the click on the div counts too an opens it again...

**Comment by packagethief** [comment]
Likely because you have a nested `click` action:

```html
<div data-controller="dialog" data-action="click->dialog#open">
  ...
  <div class="dialog-backdrop" data-action="click->dialog#close"></div>
</div>
```

So the click to close works, but then is bubbling up to the `"click->dialog#open"`, and the `open` class is reapplied.
