### ISSUE TITLE
[v3.2.2] Input type "date" and "datetime-local" do not display initial value

### ISSUE THREAD

**Issue by Mauriceu** [hotwired/stimulus#781]
Hello, first of all thank you for this framework, its a pleasure to work with.

Version: 3.2.2

I came across an issue regarding <input> elements with type "date" and "datetime-local", but not "datetime". 
Consider the following HTML:

```html
    <input
        type="date"
        value="2024-07-30"
        data-model="debounce(700)|from"
    />
```

The "value" attribute is not rendered correctly, the <input> element just displays the expected format, in my case "tt.mm.yyyy", not "2024-07-30". Inspecting the DOM shows that the "value" attribute is set correctly, so I assume a stimulus hook is responsible for this?

The value is displayed correctly in one of these cases:
 - the "data-model" attribute is removed from the input-element
 - the user inputs a value with the datepicker
 - the user inputs a value with a keyboard

**Comment by packagethief** [comment]
It doesn't seem like this would be related to Stimulus. It doesn't have any hooks for specific elements. It could be a browser issue, or something specific to your application. Can you try creating a minimal reproduction with just HTML and Stimulus?

**Comment by Mauriceu** [comment]
Reproducer: [https://github.com/Mauriceu/symfony-issues/tree/turbo-datepicker-issue](https://github.com/Mauriceu/symfony-issues/tree/turbo-datepicker-issue)

As I probably should have mention sooner, Turbo is integrated into a symfony application. 
The relevant component "FormComponent" resides in "assets/components".
The "form.html.twig" file contains the relevant html - if you remove the "data-model", the date is displayed. Otherwise, only the format is visible.

**Comment by Mauriceu** [comment]
yea closing this, because its actually an issue with ux specific components
