### ISSUE TITLE
Value changed fires without reflecting a change

### ISSUE THREAD

**Issue by chawes13** [hotwired/stimulus#783]
## Expected
1. When setting a value for a controller, the initial value set by the server does not trigger a change callback.
2. When setting a value for a controller, the initial value set by the server does not trigger a change callback when the value differs from the default.
3. ~Callbacks are not triggered before a controller is connected.~

## Actual
1. The initial value set in `data-<controller>-<variable>-value` triggers a change callback from `""` to the value
2. The initial value set in `data-<controller>-<variable>-value` triggers a change callback from the default in the controller to the value
3. ~`<variable>ValueChanged` callbacks are invoked before `connected`~

Sandbox: https://codesandbox.io/p/devbox/floral-glitter-rpm4h3?workspaceId=52445ece-e34a-4456-9666-fecd71d29f73

Version: 3.2.2 (latest)

**Comment by adrienpoly** [comment]
I think this is by design and documented here

https://stimulus.hotwired.dev/reference/values#change-callbacks

if you need to do something before the first callback it has to be in the initialise method
